#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
------------------------------------------------------------------------------
Script Name:   bintopsy-report.py
Description:   Single-command pipeline that runs the full BinTopsy stack on
               one binary and produces a self-contained HTML report:

                 1. r2-dissector.py      → structural JSON + entropy
                 2. sda-hashes.py        → enrich JSON with TLSH
                 3. r2-call-tracer.py    → call trace JSON
                 4. json-behavior-analyzer.py
                                         → behavioural matrix
                                           + ATT&CK Navigator layer
                 5. entropy-viz.py       → entropy heatmap (PDF)
                 6. r2-dissector.py --call-graph
                                         → global call graph (PDF)
                 7. (optional) yara-chunk-scanner.py

               All outputs land in --output-dir, with index.html linking
               to every artifact.

Author:        Ricardo J. Rodríguez
Created:       2026-05-07
Version:       1.0
------------------------------------------------------------------------------
"""

import argparse
import os
import sys
import shutil
import subprocess
import time

HERE = os.path.dirname(os.path.abspath(__file__))


def step(msg):
    print(f"\n\033[1;96m=== {msg} ===\033[0m")


def run(cmd, *, capture_stdout_to=None, allow_fail=False):
    """Run a subprocess. If capture_stdout_to is set, redirect stdout to that file."""
    print(f"  $ {' '.join(cmd)}")
    start = time.time()
    if capture_stdout_to:
        with open(capture_stdout_to, 'w') as fout:
            rc = subprocess.call(cmd, stdout=fout)
    else:
        rc = subprocess.call(cmd)
    elapsed = time.time() - start
    if rc != 0 and not allow_fail:
        print(f"  [-] step failed (rc={rc}); continuing anyway")
    print(f"  ({elapsed:.1f}s)")
    return rc


def script(name):
    return [sys.executable, os.path.join(HERE, name)]


def write_index(out_dir, sample, artifacts):
    """Self-contained HTML index linking every output file."""
    rows = []
    for label, path, desc in artifacts:
        if path is None:
            rows.append(f"<tr><td>{label}</td><td>(skipped)</td><td>{desc}</td></tr>")
            continue
        rel = os.path.relpath(path, out_dir)
        # Expand if the artifact is a directory (e.g. graphs/)
        if os.path.isdir(path):
            sub_idx = os.path.join(path, "index.html")
            if os.path.exists(sub_idx):
                rel = os.path.relpath(sub_idx, out_dir)
        rows.append(f'<tr><td>{label}</td>'
                    f'<td><a href="{rel}" target="_blank">{rel}</a></td>'
                    f'<td>{desc}</td></tr>')

    html = f"""<!doctype html>
<html><head><meta charset="utf-8"><title>BinTopsy report — {sample}</title>
<style>
 body {{ font-family: -apple-system, sans-serif; margin: 2rem; max-width: 1100px; }}
 h1 {{ font-size: 1.5rem; }}
 table {{ border-collapse: collapse; width: 100%; margin-top: 1rem; }}
 th, td {{ padding: 8px 12px; border-bottom: 1px solid #ddd; text-align: left; vertical-align: top; }}
 th {{ background: #eef; }}
 tr:hover {{ background: #fffbe6; }}
 a {{ color: #08c; }}
 .meta {{ color: #666; font-size: 0.9rem; }}
</style></head>
<body>
<h1>BinTopsy report — {sample}</h1>
<p class="meta">Generated by bintopsy-report.py. Open the artifacts below.</p>
<table>
<thead><tr><th>Step</th><th>Artifact</th><th>What it shows</th></tr></thead>
<tbody>
{''.join(rows)}
</tbody></table>
</body></html>
"""
    idx_path = os.path.join(out_dir, "index.html")
    with open(idx_path, 'w') as f:
        f.write(html)
    print(f"\n[+] Index written to {idx_path}")


def main():
    parser = argparse.ArgumentParser(description="Run the full BinTopsy pipeline on one binary.")
    parser.add_argument("binary", help="Binary to analyse")
    parser.add_argument("-o", "--output-dir", required=True, help="Where to write all artifacts")
    parser.add_argument("--yara", help="Optional YARA rules file or directory.")
    parser.add_argument("--no-call-graph", action="store_true",
                        help="Skip the global call-graph step (slow on big binaries).")
    parser.add_argument("--no-graph-all", action="store_true",
                        help="Skip per-function CFG batch generation.")
    args = parser.parse_args()

    if not os.path.isfile(args.binary):
        print(f"[-] Binary not found: {args.binary}", file=sys.stderr)
        sys.exit(1)
    os.makedirs(args.output_dir, exist_ok=True)

    sample = os.path.basename(args.binary)
    artifacts = []

    # 1. Dissector
    dissect_json = os.path.join(args.output_dir, "dissect.json")
    step("1/6 Dissector → structural JSON")
    run(script("r2-dissector.py") + [args.binary], capture_stdout_to=dissect_json)
    artifacts.append(("Dissector JSON", dissect_json, "Per-function metadata, entropy, raw bytes."))

    # 2. Fuzzy hashes
    enriched_json = os.path.join(args.output_dir, "dissect_enriched.json")
    step("2/6 Fuzzy hashing (TLSH)")
    run(script("sda-hashes.py") + [dissect_json, "--tlsh", "-o", enriched_json])
    artifacts.append(("TLSH-enriched JSON", enriched_json,
                      "Same as dissector + TLSH per function. Use bintopsy-cluster on it."))

    # 3. Call tracer
    calls_json = os.path.join(args.output_dir, "calls.json")
    step("3/6 Call tracer")
    run(script("r2-call-tracer.py") + [args.binary], capture_stdout_to=calls_json)
    artifacts.append(("Call trace JSON", calls_json, "API + internal calls per function."))

    # 4. Behaviour analyser + ATT&CK
    behaviour_txt = os.path.join(args.output_dir, "behaviour.txt")
    behaviour_json = os.path.join(args.output_dir, "behaviour.json")
    attack_layer = os.path.join(args.output_dir, "attack_layer.json")
    step("4/6 Behavioural analysis + ATT&CK mapping")
    run(script("json-behavior-analyzer.py") + [
        calls_json, "--json", behaviour_json, "--attack-layer", attack_layer,
    ], capture_stdout_to=behaviour_txt)
    artifacts.append(("Behaviour matrix (text)", behaviour_txt, "Capability buckets per function."))
    artifacts.append(("Behaviour findings (JSON)", behaviour_json, "Same data, machine-readable."))
    artifacts.append(("ATT&CK Navigator layer", attack_layer,
                      "Drag into https://mitre-attack.github.io/attack-navigator/"))

    # 5. Entropy heatmap
    entropy_pdf = os.path.join(args.output_dir, "entropy.pdf")
    step("5/6 Entropy heatmap")
    run(script("entropy-viz.py") + [args.binary, "-o", entropy_pdf])
    artifacts.append(("Entropy heatmap", entropy_pdf,
                      "Per-page Shannon entropy. High blocks may indicate packing/encryption."))

    # 6. CFG gallery + global call graph
    graphs_dir = os.path.join(args.output_dir, "graphs")
    if not args.no_graph_all:
        step("6/6a Per-function CFG gallery")
        run(script("r2-dissector.py") + [args.binary, "--graph-all", "-od", graphs_dir])
        artifacts.append(("CFG gallery", graphs_dir, "One PDF per function (sorted by CC)."))
    else:
        artifacts.append(("CFG gallery", None, "Skipped (--no-graph-all)."))

    if not args.no_call_graph:
        step("6/6b Global call graph")
        run(script("r2-dissector.py") + [args.binary, "--call-graph", "-od", graphs_dir])
        artifacts.append(("Global call graph",
                          os.path.join(graphs_dir, "global_call_graph.pdf"),
                          "Whole-binary who-calls-whom map."))
    else:
        artifacts.append(("Global call graph", None, "Skipped (--no-call-graph)."))

    # 7. Optional YARA scan
    if args.yara:
        yara_txt = os.path.join(args.output_dir, "yara.txt")
        step("7/6 YARA scan (optional)")
        run(script("yara-chunk-scanner.py") + [args.binary, args.yara],
            capture_stdout_to=yara_txt)
        artifacts.append(("YARA matches", yara_txt, f"Hits from rules at {args.yara}"))

    write_index(args.output_dir, sample, artifacts)


if __name__ == "__main__":
    main()
