#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
------------------------------------------------------------------------------
Script Name:   disasm.py
Description:   A CLI Disassembler using Capstone Engine. Accepts binary files
               or raw hex strings (including mixed ASCII/Hex dumps).

Author:        Generated by Google Gemini, Revised by Ricardo J. Rodríguez
Created:       2025-11-23
Version:       1.1

Requirements:  pip install capstone
------------------------------------------------------------------------------
"""

import argparse
import sys
import re
import os
from capstone import (
    Cs, CsError,
    CS_ARCH_X86, CS_ARCH_ARM, CS_ARCH_ARM64, CS_ARCH_MIPS,
    CS_MODE_16, CS_MODE_32, CS_MODE_64,
    CS_MODE_ARM, CS_MODE_THUMB, CS_MODE_MIPS32, CS_MODE_MIPS64,
    CS_MODE_LITTLE_ENDIAN, CS_MODE_BIG_ENDIAN,
)

# Mapping CLI strings to (Capstone arch, base mode)
ARCH_MAP = {
    'x16':       (CS_ARCH_X86,   CS_MODE_16),
    'x86':       (CS_ARCH_X86,   CS_MODE_32),
    'x64':       (CS_ARCH_X86,   CS_MODE_64),
    'arm':       (CS_ARCH_ARM,   CS_MODE_ARM),
    'arm_thumb': (CS_ARCH_ARM,   CS_MODE_THUMB),
    'arm64':     (CS_ARCH_ARM64, CS_MODE_ARM),
    'mips':      (CS_ARCH_MIPS,  CS_MODE_MIPS32),
    'mips64':    (CS_ARCH_MIPS,  CS_MODE_MIPS64),
}


def clean_hex_input(raw_input):
    """
    Extracts valid hex bytes from a messy string.

    Handles inputs like '\\x55\\x48...', '0x55,0x48' or hexdump rows where
    the printable-ASCII column would otherwise pollute the byte stream.

    Strategy:
      1. Strip common byte separators ("0x", "\\x", commas).
      2. Match standalone 2-char hex tokens with word boundaries.
      3. Fallback to a hex-only filter if step 2 yields nothing.
    """
    raw_input = raw_input.replace("0x", " ").replace("\\x", " ").replace(",", " ")

    hex_tokens = re.findall(r'\b[0-9a-fA-F]{2}\b', raw_input)

    if not hex_tokens:
        stripped = re.sub(r'[^0-9a-fA-F]', '', raw_input)
        hex_tokens = [stripped[i:i + 2] for i in range(0, len(stripped) - 1, 2)]

    try:
        return bytes.fromhex("".join(hex_tokens))
    except ValueError:
        print("[-] Error: Could not parse input as Hex.", file=sys.stderr)
        sys.exit(1)


def build_disassembler(arch_name, big_endian=False):
    """Builds a Capstone Cs() instance from CLI arch name + endianness."""
    arch_const, mode_const = ARCH_MAP[arch_name]

    # Endianness only meaningful for ARM/MIPS; x86 ignores it.
    if arch_const in (CS_ARCH_ARM, CS_ARCH_ARM64, CS_ARCH_MIPS):
        mode_const |= (CS_MODE_BIG_ENDIAN if big_endian else CS_MODE_LITTLE_ENDIAN)

    return Cs(arch_const, mode_const)


def disassemble(code_bytes, md, address=0x1000, max_count=0):
    print(f"\n{'OFFSET':<12} {'BYTES':<24} {'OPCODE':<10} OPERANDS")
    print("-" * 72)

    count = 0
    for i in md.disasm(code_bytes, address):
        byte_str = " ".join(f"{b:02x}" for b in i.bytes)
        print(f"0x{i.address:08x}   {byte_str:<24} {i.mnemonic:<10} {i.op_str}")
        count += 1
        if max_count and count >= max_count:
            break

    if count == 0:
        print("[-] No valid instructions decoded. Wrong arch/endianness?",
              file=sys.stderr)


def parse_hex_int(value):
    """argparse type for integers expressed in hex (0x...) or decimal."""
    try:
        return int(value, 0)
    except ValueError:
        raise argparse.ArgumentTypeError(f"invalid integer: {value!r}")


def main():
    parser = argparse.ArgumentParser(
        description="Python Disassembler using Capstone",
    )

    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("-s", "--string", help="Hex string to disassemble (supports mixed formatting)")
    group.add_argument("-f", "--file", help="Binary file to read bytes from")

    parser.add_argument("-a", "--arch", choices=ARCH_MAP.keys(), default='x64',
                        help="Target architecture (default: x64)")
    parser.add_argument("--base", type=parse_hex_int, default=0x1000,
                        help="Base address for disassembly (default: 0x1000)")
    parser.add_argument("--big-endian", action="store_true",
                        help="Use big-endian mode (only for ARM/MIPS)")
    parser.add_argument("-n", "--count", type=int, default=0,
                        help="Stop after N instructions (default: unlimited)")

    args = parser.parse_args()

    if args.file:
        if not os.path.isfile(args.file):
            print(f"[-] File not found: {args.file}", file=sys.stderr)
            sys.exit(1)
        with open(args.file, "rb") as f:
            code_bytes = f.read()
        if not code_bytes:
            print(f"[-] File is empty: {args.file}", file=sys.stderr)
            sys.exit(1)
    else:
        code_bytes = clean_hex_input(args.string)
        if not code_bytes:
            print("[-] Could not extract any hex bytes from the input string.",
                  file=sys.stderr)
            print("    Hint: pass bytes as '55 48 89 e5', '0x55,0x48' or '\\x55\\x48'.",
                  file=sys.stderr)
            sys.exit(1)

    try:
        md = build_disassembler(args.arch, big_endian=args.big_endian)
        md.detail = True
    except CsError as e:
        print(f"[-] Capstone init error: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"[+] Disassembling {len(code_bytes)} bytes as {args.arch}"
          f"{' (BE)' if args.big_endian else ''}...")

    try:
        disassemble(code_bytes, md, args.base, args.count)
    except CsError as e:
        print(f"[-] Capstone error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
