#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
------------------------------------------------------------------------------
Script Name:   disasm.py
Description:   A CLI Disassembler using Capstone Engine. Accepts binary files 
               or raw hex strings (including mixed ASCII/Hex dumps).

Author:        Generated by Google Gemini, Revised by Ricardo J. Rodríguez
Created:       2025-11-23
Version:       1.0

Requirements:  pip install capstone
------------------------------------------------------------------------------
"""

import argparse
import sys
import re
import os
from capstone import *

# Mapping CLI strings to Capstone Constants
ARCH_MAP = {
    'x86': (CS_ARCH_X86, CS_MODE_32),
    'x64': (CS_ARCH_X86, CS_MODE_64),
    'arm': (CS_ARCH_ARM, CS_MODE_ARM),
    'arm_thumb': (CS_ARCH_ARM, CS_MODE_THUMB),
    'arm64': (CS_ARCH_ARM64, CS_MODE_ARM),
    'mips': (CS_ARCH_MIPS, CS_MODE_MIPS32),
    'mips64': (CS_ARCH_MIPS, CS_MODE_MIPS64),
}

def clean_hex_input(raw_input):
    """
    Attempts to extract valid hex bytes from a messy string.
    It handles inputs like '55 48 ... UH...' by using regex to find 
    hex-like patterns and ignoring non-hex ascii noise.
    """
    # 1. If it looks like a standard hex string (e.g., \x55\x48 or 0x55,0x48), standardize it
    raw_input = raw_input.replace("0x", " ").replace("\\x", " ").replace(",", " ")
    
    # 2. Use regex to find all standalone 2-character hex strings.
    # This helps avoid capturing letters inside the ASCII column of a hexdump 
    # unless they are separated by spaces and look like bytes.
    # Matches: "55", "48", "8d"
    hex_tokens = re.findall(r'\b[0-9a-fA-F]{2}\b', raw_input)
    
    if not hex_tokens:
        # Fallback: try to strip everything non-hex and join
        stripped = re.sub(r'[^0-9a-fA-F]', '', raw_input)
        # Split into pairs
        hex_tokens = [stripped[i:i+2] for i in range(0, len(stripped), 2)]

    try:
        return bytes.fromhex("".join(hex_tokens))
    except ValueError:
        print("[-] Error: Could not parse input as Hex.")
        sys.exit(1)

def disassemble(code_bytes, arch_const, mode_const, address=0x1000):
    try:
        md = Cs(arch_const, mode_const)
        # Detailed mode enables retrieving operand details if needed later
        md.detail = True 
        
        print(f"\n{'OFFSET':<10} {'BYTES':<20} {'OPCODE':<10} {'OPERANDS'}")
        print("-" * 60)

        for i in md.disasm(code_bytes, address):
            # Format the bytes column (e.g., "55 48 89 e5")
            byte_str = " ".join(f"{b:02x}" for b in i.bytes)
            print(f"0x{i.address:x}:\t {byte_str:<20} {i.mnemonic:<10} {i.op_str}")
            
    except CsError as e:
        print(f"[-] Capstone Error: {e}")

def main():
    parser = argparse.ArgumentParser(description="Python Disassembler using Capstone")
    
    # Input group: either file or string
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("-s", "--string", help="Hex string to disassemble (supports mixed formatting)")
    group.add_argument("-f", "--file", help="Binary file to read bytes from")
    
    parser.add_argument("-a", "--arch", choices=ARCH_MAP.keys(), default='x64',
                        help="Target Architecture (Default: x64)")
    parser.add_argument("--base", type=str, default="0x1000", 
                        help="Base address for disassembly (Default: 0x1000)")

    args = parser.parse_args()

    # 1. Load Bytes
    code_bytes = b""
    if args.file:
        if not os.path.exists(args.file):
            print(f"[-] File not found: {args.file}")
            return
        with open(args.file, "rb") as f:
            code_bytes = f.read()
    else:
        # Clean the messy string input
        code_bytes = clean_hex_input(args.string)

    if not code_bytes:
        print("[-] No data to disassemble.")
        return

    # 2. Parse Architecture
    arch, mode = ARCH_MAP[args.arch]
    
    # 3. Parse Base Address
    try:
        base_addr = int(args.base, 16)
    except ValueError:
        base_addr = 0x1000

    print(f"[+] Disassembling {len(code_bytes)} bytes as {args.arch}...")
    disassemble(code_bytes, arch, mode, base_addr)

if __name__ == "__main__":
    main()
