# -*- coding: utf-8 -*-
"""
------------------------------------------------------------------------------
Script Name:   entropy-viz.py
Description:   Generates a 2D Shannon Entropy Heatmap from a binary file to 
               visualize packed code, encryption, or data density.

Author:        Generated by Google Gemini, Revised by Ricardo J. Rodríguez
Created:       2025-11-23
Version:       1.0

Requirements:  pip install matplotlib numpy
------------------------------------------------------------------------------
"""
import argparse
import math
import os
import numpy as np
import matplotlib.pyplot as plt

OUTPUT_FILE='entropy_heatmap.pdf'

def calculate_shannon_entropy(data):
    """
    Calculates the Shannon entropy of a numpy array of bytes.
    Returns a float between 0.0 and 8.0.
    """
    if len(data) == 0:
        return 0.0
    
    # Count frequency of each byte value (0-255)
    _, counts = np.unique(data, return_counts=True)
    
    # Calculate probabilities
    probabilities = counts / len(data)
    
    # Calculate entropy: -SUM(p * log2(p))
    entropy = -np.sum(probabilities * np.log2(probabilities))
    
    return entropy

def main():
    parser = argparse.ArgumentParser(description="Generate a 2D Entropy Heatmap of a binary file.")
    
    parser.add_argument("file", help="Path to the binary file to analyze")
    parser.add_argument("-w", "--window", type=int, default=4096, 
                        help="Window size in bytes (Default: 4096, typical PAGE_SIZE)")
    parser.add_argument("-o", "--output", default=f"{OUTPUT_FILE}", 
                        help=f"Output filename for the heatplot (Default: {OUTPUT_FILE})")
    
    args = parser.parse_args()

    if not os.path.isfile(args.file):
        print(f"Error: File '{args.file}' not found.")
        return

    print(f"[+] Reading {args.file}...")
    print(f"[+] Calculating entropy with window size: {args.window}")

    entropies = []
    
    # Process file in chunks to avoid loading massive files entirely into RAM
    # However, we store the entropy list in RAM (which is small: 1 float per 4KB)
    try:
        with open(args.file, 'rb') as f:
            while True:
                chunk = f.read(args.window)
                if not chunk:
                    break
                
                # Convert bytes to numpy array of uint8
                data_chunk = np.frombuffer(chunk, dtype=np.uint8)
                e = calculate_shannon_entropy(data_chunk)
                entropies.append(e)
                
    except Exception as e:
        print(f"[-] Error processing file: {e}")
        return

    if not entropies:
        print("[-] File is empty.")
        return

    # --- Prepare Data for 2D Heatmap ---
    # To make a heatmap, we need a 2D grid. We calculate the square root of the 
    # number of chunks to make a roughly square image.
    
    num_chunks = len(entropies)
    grid_side = int(math.ceil(math.sqrt(num_chunks)))
    
    print(f"[+] chunks: {num_chunks} | Grid dimensions: {grid_side}x{grid_side}")

    # Pad the array with 0s (or 8s? usually 0 is better for padding) to fit the square
    padding_needed = (grid_side * grid_side) - num_chunks
    entropies_array = np.array(entropies)
    
    # Pad with 0 (low entropy) for the empty space at the end of the image
    entropies_padded = np.pad(entropies_array, (0, padding_needed), mode='constant', constant_values=0)
    
    # Reshape into 2D grid
    heatmap_data = entropies_padded.reshape((grid_side, grid_side))

    # --- Plotting ---
    print(f"[+] Generating heatplot: {args.output}")
    
    plt.figure(figsize=(10, 8))
    
    # 'inferno' or 'jet' are good colormaps. 
    # 0 (Black/Purple) = Low Entropy (Padding/Text)
    # 8 (Bright/Yellow) = High Entropy (Encryption/Compressed)
    plt.imshow(heatmap_data, cmap='inferno', interpolation='nearest', vmin=0, vmax=8)
    
    cbar = plt.colorbar()
    cbar.set_label('Shannon Entropy (Bits per Byte)')
    
    plt.title(f'Entropy Map: {os.path.basename(args.file)}\nWindow Size: {args.window} bytes')
    plt.axis('off') # Hide axis numbers as they represent arbitrary block indices
    
    plt.tight_layout()
    plt.savefig(args.output, dpi=300)
    print("[+] Done.")

if __name__ == "__main__":
    main()
