#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
------------------------------------------------------------------------------
Script Name:   entropy-viz.py
Description:   Generates a 2D Shannon Entropy Heatmap from a binary file to
               visualize packed code, encryption, or data density.

Author:        Generated by Google Gemini, Revised by Ricardo J. Rodríguez
Created:       2025-11-23
Version:       1.1

Requirements:  pip install matplotlib numpy
------------------------------------------------------------------------------
"""
import argparse
import os
import sys

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap

DEFAULT_OUTPUT = "entropy_heatmap.pdf"
DEFAULT_WINDOW = 4096          # Bytes per Shannon-entropy sample.
DEFAULT_GRID_WIDTH = 64        # Columns in the 2D heatmap.


def calculate_shannon_entropy(data):
    """Shannon entropy of a uint8 numpy array. Returns 0.0 .. 8.0."""
    if data.size == 0:
        return 0.0
    _, counts = np.unique(data, return_counts=True)
    probabilities = counts / data.size
    return float(-np.sum(probabilities * np.log2(probabilities)))


def compute_entropies(filepath, window):
    """Streams the file in `window`-sized chunks and returns a list of entropies."""
    entropies = []
    with open(filepath, 'rb') as f:
        while True:
            chunk = f.read(window)
            if not chunk:
                break
            data_chunk = np.frombuffer(chunk, dtype=np.uint8)
            entropies.append(calculate_shannon_entropy(data_chunk))
    return entropies


def main():
    parser = argparse.ArgumentParser(
        description="Generate a 2D Entropy Heatmap of a binary file.",
    )
    parser.add_argument("file", help="Path to the binary file to analyze")
    parser.add_argument("-w", "--window", type=int, default=DEFAULT_WINDOW,
                        help=f"Window size in bytes per sample (default: {DEFAULT_WINDOW})")
    parser.add_argument("-W", "--grid-width", type=int, default=DEFAULT_GRID_WIDTH,
                        help=f"Number of columns in the heatmap (default: {DEFAULT_GRID_WIDTH})")
    parser.add_argument("-o", "--output", default=DEFAULT_OUTPUT,
                        help=f"Output filename (default: {DEFAULT_OUTPUT})")
    parser.add_argument("--dpi", type=int, default=300, help="Output DPI (default: 300)")
    args = parser.parse_args()

    if not os.path.isfile(args.file):
        print(f"[-] File '{args.file}' not found.", file=sys.stderr)
        sys.exit(1)

    if args.window <= 0 or args.grid_width <= 0:
        print("[-] window and grid-width must be > 0", file=sys.stderr)
        sys.exit(1)

    file_size = os.path.getsize(args.file)
    print(f"[+] Reading {args.file} ({file_size} bytes)")
    print(f"[+] Window size: {args.window} bytes  |  Grid width: {args.grid_width} cols")

    entropies = compute_entropies(args.file, args.window)
    if not entropies:
        print("[-] File is empty.", file=sys.stderr)
        sys.exit(1)

    # Reshape into a rectangular grid: width fixed, height grows with file size.
    # Padding is masked out so it doesn't appear as a fake low-entropy region.
    width = args.grid_width
    height = (len(entropies) + width - 1) // width
    pad = width * height - len(entropies)

    arr = np.array(entropies, dtype=np.float32)
    arr = np.pad(arr, (0, pad), mode='constant', constant_values=np.nan)
    grid = arr.reshape((height, width))

    print(f"[+] Chunks: {len(entropies)}  |  Grid: {height} rows x {width} cols")
    print(f"[+] Generating heatmap: {args.output}")

    fig, ax = plt.subplots(figsize=(10, max(2, height * 10 / max(width, 1) * 0.6)))

    # 'inferno' has good perceptual range; NaN (padding) renders transparent.
    cmap = plt.get_cmap('inferno').copy()
    cmap.set_bad(color='white', alpha=0.0)

    im = ax.imshow(grid, cmap=cmap, interpolation='nearest',
                   vmin=0, vmax=8, aspect='auto')

    cbar = fig.colorbar(im, ax=ax)
    cbar.set_label('Shannon Entropy (bits per byte)')

    bytes_per_row = width * args.window
    ax.set_title(f"Entropy Map: {os.path.basename(args.file)}\n"
                 f"Window: {args.window} B  |  Row stride: {bytes_per_row} B")
    ax.set_xlabel(f"Column (each cell = {args.window} B)")
    ax.set_ylabel(f"Row (each row = {bytes_per_row} B)")

    fig.tight_layout()
    fig.savefig(args.output, dpi=args.dpi)
    print("[+] Done.")


if __name__ == "__main__":
    main()
