#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
------------------------------------------------------------------------------
Script Name:   json-behavior-analyzer.py
Description:   Parses the call-trace JSON and generates a Behavioral Matrix.
               Classifies API calls into categories (File, Network, Process, etc.)
               to identify the purpose of each function.

Author:        Generated by Google Gemini, Revised by [YOUR NAME]
Created:       2025-11-26
Version:       1.0

Requirements:  Standard Python 3 (No pip install needed)
------------------------------------------------------------------------------
"""

import json
import argparse
import sys
import os
import re
from collections import Counter

# --- Configuration: API Categories ---
# You can extend this list with more specific malware APIs.
API_CATEGORIES = {
    "FILES": [
        "CreateFile", "WriteFile", "ReadFile", "DeleteFile", "CopyFile", 
        "MoveFile", "GetTempPath", "FindFirstFile", "SetFilePointer"
    ],
    "NETWORK": [
        "socket", "connect", "send", "recv", "bind", "listen", "accept",
        "InternetOpen", "HttpSendRequest", "InternetReadFile", "URLDownload",
        "gethostbyname", "WSAStartup"
    ],
    "PROCESS": [
        "CreateProcess", "OpenProcess", "ShellExecute", "WinExec", 
        "TerminateProcess", "CreateThread", "ResumeThread", "SetThreadContext",
        "VirtualAllocEx", "WriteProcessMemory" # Injection indicators
    ],
    "REGISTRY": [
        "RegOpenKey", "RegSetValue", "RegCreateKey", "RegQueryValue", 
        "RegDeleteValue", "RegCloseKey"
    ],
    "SERVICES": [
        "OpenSCManager", "CreateService", "StartService", "ControlService",
        "OpenService"
    ],
    "MEMORY": [
        "VirtualAlloc", "VirtualProtect", "HeapAlloc", "GlobalAlloc", 
        "LocalAlloc", "RtlMoveMemory"
    ],
    "CRYPTO": [
        "CryptAcquireContext", "CryptEncrypt", "CryptDecrypt", "CryptHashData",
        "CryptCreateHash", "CryptDeriveKey"
    ],
    "GUI/USER": [
        "MessageBox", "GetWindowText", "SetWindowsHook", "GetAsyncKeyState",
        "GetForegroundWindow"
    ]
}

def clean_api_name(raw_name):
    """
    Removes prefixes like 'sym.imp.', 'KERNEL32.dll_', etc.
    Returns a clean name for matching (e.g., 'WriteFile').
    """
    # Remove standard r2 prefixes
    name = re.sub(r'^(sym\.|imp\.|reloc\.)', '', raw_name)
    # Remove DLL prefixes (e.g. KERNEL32.dll_WriteFile -> WriteFile)
    name = re.sub(r'^[a-zA-Z0-9]+\.dll_', '', name, flags=re.IGNORECASE)
    # Remove trailing decorations (e.g. @4, A, W) roughly
    # We keep A/W suffix usually, but strict matching ignores it below.
    return name

def classify_api(raw_name):
    """Returns the category name for a given API string."""
    clean = clean_api_name(raw_name).lower()
    
    for category, keywords in API_CATEGORIES.items():
        for k in keywords:
            # Check if keyword is inside the cleaned name
            # e.g. "CreateFile" in "CreateFileA"
            if k.lower() in clean:
                return category
    
    return "OTHER"

def analyze_json(json_path, verbose=False):
    if not os.path.exists(json_path):
        print("[-] JSON file not found.")
        sys.exit(1)

    try:
        with open(json_path, 'r') as f:
            data = json.load(f)
    except Exception as e:
        print(f"[-] Error loading JSON: {e}")
        sys.exit(1)

    functions = data.get("functions", [])
    print(f"[+] Loaded {len(functions)} functions. Analyzing behaviors...\n")

    # Header Format
    header_fmt = "{:<25} | {:<8} | {:<6} | {:<6} | {:<6} | {:<6} | {:<6} | {:<6}"
    print("-" * 100)
    print(header_fmt.format("FUNCTION", "COMPLEX", "FILE", "NET", "PROC", "MEM", "REG", "CRYPT"))
    print("-" * 100)

    suspicious_funcs = 0

    for func in functions:
        f_name = func.get("name", "unknown")
        # Truncate name if too long
        if len(f_name) > 24: f_name = f_name[:21] + "..."
        
        f_cc = func.get("cc", 0)
        api_calls = func.get("api_calls", [])

        if not api_calls:
            continue

        # Initialize counters for this function
        stats = Counter()

        for call in api_calls:
            target = call.get("target", "")
            category = classify_api(target)
            stats[category] += 1

        # Logic to filter noise: Show only if it has interesting categories
        # Sum of interesting counts
        total_interesting = (stats["FILES"] + stats["NETWORK"] + stats["PROCESS"] + 
                             stats["MEMORY"] + stats["REGISTRY"] + stats["CRYPTO"])
        
        if total_interesting == 0 and not verbose:
            continue

        suspicious_funcs += 1
        
        # Determine Row Color based on capabilities
        row_prefix = ""
        # Highlighting logic
        if stats["NETWORK"] > 0 and stats["FILES"] > 0:
            row_prefix = "\033[93m" # Yellow (Dropper?)
        if stats["CRYPTO"] > 0 and stats["FILES"] > 0:
            row_prefix = "\033[91m" # Red (Ransomware?)
        if stats["PROCESS"] > 0 and stats["MEMORY"] > 0:
            row_prefix = "\033[95m" # Magenta (Injector?)
        
        RESET = "\033[0m"

        print(f"{row_prefix}" + header_fmt.format(
            f_name, 
            f_cc,
            stats["FILES"] if stats["FILES"] else "-",
            stats["NETWORK"] if stats["NETWORK"] else "-",
            stats["PROCESS"] if stats["PROCESS"] else "-",
            stats["MEMORY"] if stats["MEMORY"] else "-",
            stats["REGISTRY"] if stats["REGISTRY"] else "-",
            stats["CRYPTO"] if stats["CRYPTO"] else "-"
        ) + f"{RESET}")

    print("-" * 100)
    print(f"[+] Found {suspicious_funcs} functions with interesting behavioral patterns.")
    print("    (Use --verbose to see functions with only GUI/Other calls)")

def main():
    parser = argparse.ArgumentParser(description="Analyze WinAPI stats per function from JSON.")
    parser.add_argument("input", help="Input JSON file (from r2-call-tracer.py)")
    parser.add_argument("-v", "--verbose", action="store_true", help="Show all functions, even those with only generic APIs")
    
    args = parser.parse_args()
    analyze_json(args.input, args.verbose)

if __name__ == "__main__":
    main()
