#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
------------------------------------------------------------------------------
Script Name:   json-behavior-analyzer.py
Description:   Parses the call-trace JSON produced by `r2-call-tracer.py` and
               builds a per-function behavioural matrix. APIs are mapped to
               high-level capability buckets (file, network, process, crypto,
               injection, anti-analysis, ...) so analysts can spot likely
               droppers, ransomware, injectors and similar patterns at a
               glance.

               v2.0 changes:
                 - Added POSIX coverage (open/read/write/socket/fork/execve/
                   ptrace/mmap/dlopen/...). Previously only Windows APIs
                   were classified, so Linux/macOS samples produced empty
                   reports.
                 - Each bucket now maps to a MITRE ATT&CK technique. Use
                   `--attack-layer FILE.json` to emit an ATT&CK Navigator
                   layer (importable at https://mitre-attack.github.io/
                   attack-navigator/).
                 - Per-function findings can be exported to JSON via
                   `--json` for downstream tooling.

Author:        Generated by Google Gemini, Revised by Ricardo J. Rodríguez
Created:       2025-11-26
Version:       2.0

Requirements:  Standard Python 3 (no pip install needed)
------------------------------------------------------------------------------
"""

import json
import argparse
import sys
import os
import re
from collections import Counter

# Colours go to stdout. Strip them when stdout is redirected to a file or
# when NO_COLOR / BINTOPSY_NO_COLOR is set, otherwise downstream tools
# (and the bintopsy-report HTML pipeline) end up with raw escape codes.
_USE_COLOR = (
    sys.stdout.isatty()
    and not os.environ.get("NO_COLOR")
    and not os.environ.get("BINTOPSY_NO_COLOR")
)


def _c(code):
    return code if _USE_COLOR else ""


C_YELLOW  = _c("\033[93m")
C_RED     = _c("\033[91m")
C_MAGENTA = _c("\033[95m")
C_CYAN    = _c("\033[96m")
C_RESET   = _c("\033[0m")

# --- Configuration: API Categories ---
# Substring matching is intentional ('CreateFile' also matches 'CreateFileA').
# Each bucket has BOTH Windows API names AND POSIX equivalents so the
# analyser is useful for Windows, Linux and macOS samples.
API_CATEGORIES = {
    "FILES": [
        # Windows
        "CreateFile", "WriteFile", "ReadFile", "DeleteFile", "CopyFile",
        "MoveFile", "GetTempPath", "FindFirstFile", "FindNextFile",
        "SetFilePointer", "GetFileSize", "GetFileAttributes", "SetFileAttributes",
        "CreateDirectory", "RemoveDirectory",
        # POSIX
        "_open", "openat", "fopen", "creat", "_read", "_write", "pread",
        "pwrite", "unlink", "rename", "lseek", "stat", "fstat", "lstat",
        "mkdir", "rmdir", "opendir", "readdir", "fts_open", "fts_read",
    ],
    "NETWORK": [
        # Windows
        "InternetOpen", "InternetConnect", "HttpOpenRequest", "HttpSendRequest",
        "InternetReadFile", "URLDownload", "URLOpenStream",
        "WinHttpOpen", "WinHttpConnect", "WinHttpSendRequest", "WinHttpReadData",
        "DnsQuery", "FtpGetFile", "FtpPutFile",
        "WSAStartup", "WSASocket",
        # POSIX (and shared with WinSock)
        "socket", "connect", "send", "sendto", "recv", "recvfrom",
        "bind", "listen", "accept", "gethostbyname", "getaddrinfo",
        "inet_aton", "inet_ntoa", "inet_pton",
    ],
    "PROCESS": [
        # Windows
        "CreateProcess", "OpenProcess", "ShellExecute", "WinExec",
        "TerminateProcess", "CreateThread", "ResumeThread", "SuspendThread",
        "ExitProcess", "GetCurrentProcess", "Process32First", "Process32Next",
        # POSIX
        "fork", "vfork", "clone", "execve", "execl", "execlp", "execvp",
        "posix_spawn", "system", "popen", "waitpid", "kill", "pthread_create",
    ],
    "INJECTION": [
        # Windows: classic + indirect process injection primitives.
        "VirtualAllocEx", "WriteProcessMemory", "ReadProcessMemory",
        "CreateRemoteThread", "QueueUserAPC", "SetThreadContext",
        "NtMapViewOfSection", "ZwMapViewOfSection",
        "NtCreateThreadEx", "ZwCreateThreadEx",
        "NtUnmapViewOfSection", "RtlCreateUserThread",
        # POSIX equivalents (ptrace-based injection, LD_PRELOAD, mmap+exec).
        "ptrace", "process_vm_writev", "process_vm_readv",
    ],
    "MEMORY": [
        # Windows
        "VirtualAlloc", "VirtualProtect", "VirtualFree", "HeapAlloc",
        "GlobalAlloc", "LocalAlloc", "RtlMoveMemory",
        # POSIX
        "mmap", "mprotect", "munmap", "mremap", "shmget", "shmat",
        "memcpy", "memset", "memcmp", "memmove",
    ],
    "REGISTRY": [
        "RegOpenKey", "RegSetValue", "RegCreateKey", "RegQueryValue",
        "RegDeleteValue", "RegDeleteKey", "RegEnumKey", "RegEnumValue",
        "RegCloseKey",
    ],
    "SERVICES": [
        # Windows
        "OpenSCManager", "CreateService", "StartService", "ControlService",
        "OpenService", "DeleteService", "QueryServiceStatus",
    ],
    "PERSISTENCE": [
        # Windows
        "CreateService", "RegSetValue", "RegCreateKey",
        "SetWindowsHook", "CreateScheduledTask",
        # POSIX (cron, systemd, launchd, .bashrc rewrites)
        "crontab", "setuid", "setgid", "atexit",
    ],
    "CRYPTO": [
        # Windows
        "CryptAcquireContext", "CryptEncrypt", "CryptDecrypt", "CryptHashData",
        "CryptCreateHash", "CryptDeriveKey", "CryptGenKey", "CryptImportKey",
        "CryptExportKey", "CryptGenRandom",
        "BCryptEncrypt", "BCryptDecrypt", "BCryptHashData", "BCryptGenRandom",
        # POSIX (OpenSSL / libgcrypt / CommonCrypto)
        "EVP_Encrypt", "EVP_Decrypt", "EVP_DigestUpdate", "EVP_PKEY",
        "AES_set_encrypt_key", "AES_encrypt", "AES_decrypt",
        "MD5_", "SHA1_", "SHA256_", "RAND_bytes",
        "CCCrypt", "CC_MD5", "CC_SHA",
    ],
    "LOADER": [
        # Dynamic resolution / shellcode loaders.
        "LoadLibrary", "GetProcAddress", "GetModuleHandle", "FreeLibrary",
        "LdrLoadDll", "LdrGetProcedureAddress",
        # POSIX
        "dlopen", "dlsym", "dlclose", "dladdr",
    ],
    "ANTI_ANALYSIS": [
        # Windows
        "IsDebuggerPresent", "CheckRemoteDebuggerPresent",
        "NtQueryInformationProcess", "ZwQueryInformationProcess",
        "OutputDebugString", "GetTickCount", "QueryPerformanceCounter",
        "FindWindow", "EnumWindows", "GetSystemInfo", "GetComputerName",
        "GetUserName",
        # POSIX
        "ptrace", "Sleep", "SleepEx", "NtDelayExecution",
        "nanosleep", "clock_gettime", "gettimeofday",
        "sysctl", "sysctlbyname", "uname",
    ],
    "GUI_USER": [
        "MessageBox", "GetWindowText", "SetWindowsHook", "GetAsyncKeyState",
        "GetForegroundWindow", "GetClipboardData", "OpenClipboard",
    ],
}

# Buckets that count toward the "this looks suspicious" filter.
SUSPICIOUS_BUCKETS = (
    "FILES", "NETWORK", "PROCESS", "INJECTION", "MEMORY",
    "REGISTRY", "CRYPTO", "LOADER", "ANTI_ANALYSIS", "PERSISTENCE",
)

# --- MITRE ATT&CK mapping ---
# Each bucket → list of ATT&CK Enterprise techniques most commonly associated
# with it. Used by --attack-layer to emit an ATT&CK Navigator JSON layer.
ATTACK_MAP = {
    "FILES":        ["T1005", "T1083"],            # Local data, file discovery
    "NETWORK":      ["T1071", "T1095"],            # App layer protocol, non-app layer
    "PROCESS":      ["T1059", "T1106"],            # Cmd & scripting, Native API
    "INJECTION":    ["T1055"],                     # Process Injection
    "MEMORY":       ["T1055.012"],                 # Process Hollowing (mmap/mprotect heavy)
    "REGISTRY":     ["T1112"],                     # Modify Registry
    "SERVICES":     ["T1543.003"],                 # Windows Service
    "PERSISTENCE":  ["T1543", "T1547"],            # Service / Boot autostart
    "CRYPTO":       ["T1486", "T1027"],            # Encrypt for impact / Obfuscated files
    "LOADER":       ["T1129", "T1574.002"],        # Shared modules / DLL side-loading
    "ANTI_ANALYSIS":["T1497", "T1622"],            # Virt/Sandbox evasion / Debugger evasion
    "GUI_USER":     ["T1056.001"],                 # Keylogging
}


def clean_api_name(raw_name):
    """Strip r2 prefixes and DLL prefixes (e.g. KERNEL32.dll_WriteFile -> WriteFile)."""
    name = re.sub(r'^(sym\.|imp\.|reloc\.)+', '', raw_name)
    name = re.sub(r'^[a-zA-Z0-9]+\.dll_', '', name, flags=re.IGNORECASE)
    return name


def classify_api(raw_name):
    clean = clean_api_name(raw_name).lower()
    for category, keywords in API_CATEGORIES.items():
        if any(k.lower() in clean for k in keywords):
            return category
    return "OTHER"


def emit_attack_layer(buckets_seen, output_path, sample_name):
    """Write an ATT&CK Navigator v4.5 layer JSON for the techniques observed."""
    techniques = []
    for bucket in sorted(buckets_seen):
        for tid in ATTACK_MAP.get(bucket, []):
            techniques.append({
                "techniqueID": tid,
                "score": 1,
                "color": "",
                "comment": f"Inferred from BinTopsy bucket: {bucket}",
                "enabled": True,
            })

    layer = {
        "name": f"BinTopsy: {sample_name}",
        "versions": {"attack": "14", "navigator": "4.9.0", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": "Auto-generated from json-behavior-analyzer.py",
        "techniques": techniques,
        "gradient": {"colors": ["#ffe766", "#ff6666"], "minValue": 0, "maxValue": 1},
        "legendItems": [{"label": "Observed via API usage", "color": "#ff6666"}],
    }

    with open(output_path, 'w') as f:
        json.dump(layer, f, indent=2)


def analyze_json(json_path, verbose=False, json_out=None, attack_layer=None):
    if not os.path.exists(json_path):
        print("[-] JSON file not found.", file=sys.stderr)
        sys.exit(1)

    try:
        with open(json_path, 'r') as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError) as e:
        print(f"[-] Error loading JSON: {e}", file=sys.stderr)
        sys.exit(1)

    functions = data.get("functions", [])
    sample_name = data.get("metadata", {}).get("filename", os.path.basename(json_path))
    print(f"[+] Loaded {len(functions)} functions from '{sample_name}'. Analyzing...\n")

    header_fmt = "{:<25} | {:<7} | {:<5} | {:<4} | {:<4} | {:<3} | {:<3} | {:<3} | {:<5} | {:<5} | {:<3}"
    columns = ("FUNCTION", "COMPLEX", "FILE", "NET", "PROC", "INJ", "MEM", "REG", "CRYPT", "LOADER", "AA")
    print("-" * 110)
    print(header_fmt.format(*columns))
    print("-" * 110)

    suspicious_funcs = 0

    findings = []           # for --json
    global_buckets = set()  # for --attack-layer

    for func in functions:
        f_name = func.get("name", "unknown")
        if len(f_name) > 24:
            display_name = f_name[:21] + "..."
        else:
            display_name = f_name

        f_cc = func.get("cc", 0)
        api_calls = func.get("api_calls", [])
        if not api_calls:
            continue

        stats = Counter()
        for call in api_calls:
            stats[classify_api(call.get("target", ""))] += 1

        total_interesting = sum(stats[b] for b in SUSPICIOUS_BUCKETS)
        if total_interesting == 0 and not verbose:
            continue

        suspicious_funcs += 1
        for b in SUSPICIOUS_BUCKETS:
            if stats[b]:
                global_buckets.add(b)

        # Highlighting (most specific patterns checked LAST so they win).
        row_prefix = ""
        if stats["NETWORK"] > 0 and stats["FILES"] > 0:
            row_prefix = C_YELLOW   # Dropper / downloader
        if stats["CRYPTO"] > 0 and stats["FILES"] > 0:
            row_prefix = C_RED      # Ransomware-like
        if stats["INJECTION"] > 0:
            row_prefix = C_MAGENTA  # Injector
        if stats["ANTI_ANALYSIS"] >= 3:
            row_prefix = C_CYAN     # Heavy anti-analysis

        def show(bucket):
            return stats[bucket] if stats[bucket] else "-"

        print(row_prefix + header_fmt.format(
            display_name, f_cc,
            show("FILES"), show("NETWORK"), show("PROCESS"), show("INJECTION"),
            show("MEMORY"), show("REGISTRY"), show("CRYPTO"),
            show("LOADER"), show("ANTI_ANALYSIS"),
        ) + C_RESET)

        findings.append({
            "function": f_name,
            "cc": f_cc,
            "buckets": {b: stats[b] for b in stats if stats[b]},
        })

    print("-" * 110)
    print(f"[+] Found {suspicious_funcs} functions with interesting behavioural patterns.")
    print("    (Use --verbose to also show GUI/Other-only functions.)")

    if json_out:
        with open(json_out, 'w') as f:
            json.dump({"sample": sample_name, "findings": findings}, f, indent=2)
        print(f"[+] Findings written to {json_out}")

    if attack_layer:
        emit_attack_layer(global_buckets, attack_layer, sample_name)
        print(f"[+] ATT&CK Navigator layer written to {attack_layer}")
        print(f"    Import at https://mitre-attack.github.io/attack-navigator/")


def main():
    parser = argparse.ArgumentParser(description="Behavioural matrix from a r2-call-tracer JSON.")
    parser.add_argument("input", help="Input JSON file (from r2-call-tracer.py)")
    parser.add_argument("-v", "--verbose", action="store_true",
                        help="Show all functions, even those with only generic APIs.")
    parser.add_argument("--json", dest="json_out", metavar="FILE",
                        help="Also write per-function findings to JSON.")
    parser.add_argument("--attack-layer", metavar="FILE",
                        help="Emit a MITRE ATT&CK Navigator layer JSON.")
    args = parser.parse_args()
    analyze_json(args.input, args.verbose, args.json_out, args.attack_layer)


if __name__ == "__main__":
    main()
