#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
------------------------------------------------------------------------------
Script Name:   json-behavior-analyzer.py
Description:   Parses the call-trace JSON produced by `r2-call-tracer.py` and
               builds a per-function behavioural matrix. APIs are mapped to
               high-level capability buckets (file, network, process, crypto,
               injection, anti-analysis, ...) so analysts can spot likely
               droppers, ransomware, injectors and similar patterns at a
               glance.

               v1.1 changes:
                 - Significantly expanded API_CATEGORIES (LOADER, INJECTION,
                   ANTI_ANALYSIS, PERSISTENCE, plus more entries in the
                   existing buckets).
                 - Highlights anti-analysis-heavy functions in a distinct
                   colour (cyan).

Author:        Generated by Google Gemini, Revised by Ricardo J. Rodríguez
Created:       2025-11-26
Version:       1.1

Requirements:  Standard Python 3 (no pip install needed)
------------------------------------------------------------------------------
"""

import json
import argparse
import sys
import os
import re
from collections import Counter

# --- Configuration: API Categories ---
# Substring matching is intentional: 'CreateFile' also matches 'CreateFileA'.
# Order within each list does not matter.
API_CATEGORIES = {
    "FILES": [
        "CreateFile", "WriteFile", "ReadFile", "DeleteFile", "CopyFile",
        "MoveFile", "GetTempPath", "FindFirstFile", "FindNextFile",
        "SetFilePointer", "GetFileSize", "GetFileAttributes", "SetFileAttributes",
        "CreateDirectory", "RemoveDirectory",
    ],
    "NETWORK": [
        "socket", "connect", "send", "recv", "bind", "listen", "accept",
        "InternetOpen", "InternetConnect", "HttpOpenRequest", "HttpSendRequest",
        "InternetReadFile", "URLDownload", "URLOpenStream",
        "WinHttpOpen", "WinHttpConnect", "WinHttpSendRequest", "WinHttpReadData",
        "gethostbyname", "getaddrinfo", "WSAStartup", "WSASocket",
        "DnsQuery", "FtpGetFile", "FtpPutFile",
    ],
    "PROCESS": [
        "CreateProcess", "OpenProcess", "ShellExecute", "WinExec",
        "TerminateProcess", "CreateThread", "ResumeThread", "SuspendThread",
        "ExitProcess", "GetCurrentProcess", "Process32First", "Process32Next",
    ],
    "INJECTION": [
        # Classic + indirect process injection primitives.
        "VirtualAllocEx", "WriteProcessMemory", "ReadProcessMemory",
        "CreateRemoteThread", "QueueUserAPC", "SetThreadContext",
        "NtMapViewOfSection", "ZwMapViewOfSection",
        "NtCreateThreadEx", "ZwCreateThreadEx",
        "NtUnmapViewOfSection", "RtlCreateUserThread",
    ],
    "MEMORY": [
        "VirtualAlloc", "VirtualProtect", "VirtualFree", "HeapAlloc",
        "GlobalAlloc", "LocalAlloc", "RtlMoveMemory", "memcpy", "memset",
    ],
    "REGISTRY": [
        "RegOpenKey", "RegSetValue", "RegCreateKey", "RegQueryValue",
        "RegDeleteValue", "RegDeleteKey", "RegEnumKey", "RegEnumValue",
        "RegCloseKey",
    ],
    "SERVICES": [
        "OpenSCManager", "CreateService", "StartService", "ControlService",
        "OpenService", "DeleteService", "QueryServiceStatus",
    ],
    "PERSISTENCE": [
        # Hits via subkey strings won't show; this catches common API surface.
        "CreateService", "RegSetValue", "RegCreateKey",
        "SetWindowsHook", "CreateScheduledTask",
    ],
    "CRYPTO": [
        "CryptAcquireContext", "CryptEncrypt", "CryptDecrypt", "CryptHashData",
        "CryptCreateHash", "CryptDeriveKey", "CryptGenKey", "CryptImportKey",
        "CryptExportKey", "CryptGenRandom",
        "BCryptEncrypt", "BCryptDecrypt", "BCryptHashData", "BCryptGenRandom",
    ],
    "LOADER": [
        # Dynamic resolution / shellcode loaders.
        "LoadLibrary", "GetProcAddress", "GetModuleHandle", "FreeLibrary",
        "LdrLoadDll", "LdrGetProcedureAddress",
    ],
    "ANTI_ANALYSIS": [
        "IsDebuggerPresent", "CheckRemoteDebuggerPresent",
        "NtQueryInformationProcess", "ZwQueryInformationProcess",
        "OutputDebugString", "GetTickCount", "QueryPerformanceCounter",
        "Sleep", "SleepEx", "NtDelayExecution",
        "FindWindow", "EnumWindows", "GetSystemInfo", "GetComputerName",
        "GetUserName",
    ],
    "GUI_USER": [
        "MessageBox", "GetWindowText", "SetWindowsHook", "GetAsyncKeyState",
        "GetForegroundWindow", "GetClipboardData", "OpenClipboard",
    ],
}

# Buckets that count toward the "this looks suspicious" filter.
SUSPICIOUS_BUCKETS = (
    "FILES", "NETWORK", "PROCESS", "INJECTION", "MEMORY",
    "REGISTRY", "CRYPTO", "LOADER", "ANTI_ANALYSIS", "PERSISTENCE",
)


def clean_api_name(raw_name):
    """Strip r2 prefixes and DLL prefixes (e.g. KERNEL32.dll_WriteFile -> WriteFile)."""
    name = re.sub(r'^(sym\.|imp\.|reloc\.)+', '', raw_name)
    name = re.sub(r'^[a-zA-Z0-9]+\.dll_', '', name, flags=re.IGNORECASE)
    return name


def classify_api(raw_name):
    clean = clean_api_name(raw_name).lower()
    for category, keywords in API_CATEGORIES.items():
        if any(k.lower() in clean for k in keywords):
            return category
    return "OTHER"


def analyze_json(json_path, verbose=False):
    if not os.path.exists(json_path):
        print("[-] JSON file not found.", file=sys.stderr)
        sys.exit(1)

    try:
        with open(json_path, 'r') as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError) as e:
        print(f"[-] Error loading JSON: {e}", file=sys.stderr)
        sys.exit(1)

    functions = data.get("functions", [])
    print(f"[+] Loaded {len(functions)} functions. Analyzing behaviours...\n")

    header_fmt = "{:<25} | {:<7} | {:<5} | {:<4} | {:<4} | {:<3} | {:<3} | {:<3} | {:<5} | {:<5} | {:<3}"
    columns = ("FUNCTION", "COMPLEX", "FILE", "NET", "PROC", "INJ", "MEM", "REG", "CRYPT", "LOADER", "AA")
    print("-" * 110)
    print(header_fmt.format(*columns))
    print("-" * 110)

    suspicious_funcs = 0
    RESET = "\033[0m"

    for func in functions:
        f_name = func.get("name", "unknown")
        if len(f_name) > 24:
            f_name = f_name[:21] + "..."

        f_cc = func.get("cc", 0)
        api_calls = func.get("api_calls", [])
        if not api_calls:
            continue

        stats = Counter()
        for call in api_calls:
            stats[classify_api(call.get("target", ""))] += 1

        total_interesting = sum(stats[b] for b in SUSPICIOUS_BUCKETS)
        if total_interesting == 0 and not verbose:
            continue

        suspicious_funcs += 1

        # Highlighting: more specific patterns checked LAST so they win.
        row_prefix = ""
        if stats["NETWORK"] > 0 and stats["FILES"] > 0:
            row_prefix = "\033[93m"  # Yellow → dropper / downloader
        if stats["CRYPTO"] > 0 and stats["FILES"] > 0:
            row_prefix = "\033[91m"  # Red → ransomware-like
        if stats["INJECTION"] > 0:
            row_prefix = "\033[95m"  # Magenta → injector
        if stats["ANTI_ANALYSIS"] >= 3:
            row_prefix = "\033[96m"  # Cyan → heavy anti-analysis

        def show(bucket):
            return stats[bucket] if stats[bucket] else "-"

        print(row_prefix + header_fmt.format(
            f_name, f_cc,
            show("FILES"), show("NETWORK"), show("PROCESS"), show("INJECTION"),
            show("MEMORY"), show("REGISTRY"), show("CRYPTO"),
            show("LOADER"), show("ANTI_ANALYSIS"),
        ) + RESET)

    print("-" * 110)
    print(f"[+] Found {suspicious_funcs} functions with interesting behavioural patterns.")
    print("    (Use --verbose to also show GUI/Other-only functions.)")


def main():
    parser = argparse.ArgumentParser(description="Behavioural matrix from a r2-call-tracer JSON.")
    parser.add_argument("input", help="Input JSON file (from r2-call-tracer.py)")
    parser.add_argument("-v", "--verbose", action="store_true",
                        help="Show all functions, even those with only generic APIs.")
    args = parser.parse_args()
    analyze_json(args.input, args.verbose)


if __name__ == "__main__":
    main()
