#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
------------------------------------------------------------------------------
Script Name:   r2-call-tracer.py (v1.1)
Description:   Iterates through EVERY function to trace calls.
               
               FIX v1.1: Added support for INDIRECT CALLS (ff15...)
               Common in Windows PE (IAT calls).
               Uses Regex to extract 'sym.imp...' from disassembly string.

Author:        Generated by Google Gemini, Revised by Ricardo J. Rodríguez
Created:       2025-11-26
Version:       1.1

Requirements:  pip install r2pipe
------------------------------------------------------------------------------
"""

import r2pipe
import argparse
import sys
import json
import os
import re

def log(msg):
    sys.stderr.write(f"[+] {msg}\n")

def is_import_name(name):
    """Heuristic to detect if a symbol name looks like an API/Import."""
    if not name: return False
    name = name.lower()
    indicators = ['imp.', 'sym.imp', 'reloc.', '.dll', 'api.']
    return any(ind in name for ind in indicators)

def analyze_calls(filename, pretty_print=True):
    log(f"Opening binary: {filename}")
    try:
        r2 = r2pipe.open(filename, flags=['-2'])
    except Exception as e:
        sys.stderr.write(f"[-] Error: {e}\n")
        sys.exit(1)

    log("Running analysis (aaa)...")
    r2.cmd('aaa')
    
    # Pre-cargar flags de imports para agilizar
    r2.cmd("fs imports; f") 

    log("Fetching function list...")
    funcs = r2.cmdj('aflj')
    
    if not funcs:
        sys.stderr.write("[-] No functions found.\n")
        return

    total_funcs = len(funcs)
    log(f"Processing {total_funcs} functions...")

    output_data = {
        "metadata": {
            "filename": os.path.basename(filename),
            "total_functions": total_funcs
        },
        "functions": []
    }

    count = 0

    for f in funcs:
        f_name = f.get('name', 'unknown')
        f_addr = f.get('offset')
        f_cc = f.get('cc', 0)

        func_entry = {
            "name": f_name,
            "addr": hex(f_addr),
            "cc": f_cc,
            "api_calls": [],
            "internal_calls": []
        }

        # Desensamblar función
        ops = r2.cmdj(f"pdfj @ {f_addr}")
        
        if ops and 'ops' in ops:
            for op in ops['ops']:
                
                # Detectar CALL (Directo o Indirecto/ucall)
                # 'ucall' es común para saltos indirectos o llamadas via registro
                if op.get('type') in ['call', 'ucall', 'ujmp', 'cjmp']: 
                    # Nota: A veces r2 marca un call a IAT como 'ucall' o incluso 'mjmp' dependiendo la arch
                    # Pero en x86/x64 'call' suele bastar. Si fallase, miramos el opcode mnemonic.
                    if 'call' not in op.get('opcode', '').lower() and op.get('type') != 'call':
                        continue

                # Validamos si es un CALL real mirando el mnemónico (disasm) por seguridad
                disasm = op.get('disasm', '')
                if not disasm.startswith('call'):
                    continue

                target_name = None
                target_addr = None
                
                # ESTRATEGIA 1: Extracción por Regex (La más efectiva para tu caso)
                # Busca: sym.imp.Algo o imp.Algo dentro de corchetes o sueltos
                # Ej: call dword [sym.imp.KERNEL32.dll_Sleep]
                match = re.search(r'((sym\.|imp\.|reloc\.)[a-zA-Z0-9_\.]+(?<!\]))', disasm)
                if match:
                    target_name = match.group(1)
                
                # ESTRATEGIA 2: Campos 'jump' o 'ptr'
                if not target_name:
                    # jump = destino directo (E8...)
                    # ptr  = destino indirecto (FF15...) -> Importante para IAT
                    addr_candidate = op.get('jump')
                    if not addr_candidate:
                        addr_candidate = op.get('ptr')
                    
                    if addr_candidate:
                        target_addr = addr_candidate
                        # Resolver flag en esa dirección
                        flags = r2.cmdj(f"fdj @ {target_addr}")
                        if flags:
                            target_name = flags.get('name')

                # Si no encontramos nombre, usamos la dirección como nombre
                final_target = target_name if target_name else (hex(target_addr) if target_addr else "Unresolved")

                call_obj = {
                    "offset": hex(op.get('offset')),
                    "instruction": disasm, # Guardamos la instrucción completa para debug
                    "target": final_target
                }

                if target_name and is_import_name(target_name):
                    func_entry["api_calls"].append(call_obj)
                else:
                    func_entry["internal_calls"].append(call_obj)

        if func_entry["api_calls"] or func_entry["internal_calls"]:
            output_data["functions"].append(func_entry)

        count += 1
        if count % 20 == 0:
            sys.stderr.write(f"\r[+] Progress: {count}/{total_funcs}")

    sys.stderr.write("\n")
    print(json.dumps(output_data, indent=4 if pretty_print else None))

def main():
    parser = argparse.ArgumentParser(description="Robust Call Tracer (Handles Indirect Calls/IAT)")
    parser.add_argument("binary", help="Path to binary file")
    
    args = parser.parse_args()

    if not os.path.exists(args.binary):
        sys.stderr.write("[-] File not found.\n")
        sys.exit(1)

    analyze_calls(args.binary)

if __name__ == "__main__":
    main()