#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
------------------------------------------------------------------------------
Script Name:   r2-call-tracer.py
Description:   Iterates through every analyzed function and records both the
               internal calls and the API/import calls (including indirect
               calls via the IAT, common in Windows PE binaries).

               v1.2 changes:
                 - Removed contradictory call-detection logic (the previous
                   filter accepted ucall/ujmp/cjmp but then rejected anything
                   whose disasm did not start with 'call', which discarded
                   most of them).
                 - Translated remaining Spanish comments for consistency.
                 - Cached resolved import flags to avoid repeated `fdj`
                   queries to r2.

Author:        Generated by Google Gemini, Revised by Ricardo J. Rodríguez
Created:       2025-11-26
Version:       1.2

Requirements:  pip install r2pipe
------------------------------------------------------------------------------
"""

import r2pipe
import argparse
import sys
import json
import os
import re

IMPORT_REGEX = re.compile(r'((?:sym\.|imp\.|reloc\.)[A-Za-z0-9_.]+)')


def log(msg):
    sys.stderr.write(f"[+] {msg}\n")


def is_import_name(name):
    """Heuristic to detect whether a symbol name looks like an API/import."""
    if not name:
        return False
    lname = name.lower()
    indicators = ('imp.', 'sym.imp', 'reloc.', '.dll', 'api.')
    return any(ind in lname for ind in indicators)


def resolve_target(r2, op, flag_cache):
    """
    Best-effort resolution of a call target. Returns (name_or_None, addr_or_None).

    Strategy:
      1. Regex over the disasm string for sym./imp./reloc. tokens (works for
         indirect IAT calls like `call dword [sym.imp.KERNEL32.dll_Sleep]`).
      2. Fall back to `jump` (direct E8...) or `ptr` (indirect FF15...) and
         resolve the flag at that address. Cached because hot loops were
         calling `fdj` thousands of times.
    """
    disasm = op.get('disasm', '')

    match = IMPORT_REGEX.search(disasm)
    if match:
        return match.group(1), None

    addr = op.get('jump') or op.get('ptr')
    if not addr:
        return None, None

    if addr in flag_cache:
        return flag_cache[addr], addr

    flags = r2.cmdj(f"fdj @ {addr}")
    name = flags.get('name') if isinstance(flags, dict) else None
    flag_cache[addr] = name
    return name, addr


def analyze_calls(filename, pretty_print=True):
    log(f"Opening binary: {filename}")
    try:
        r2 = r2pipe.open(filename, flags=['-2'])
    except Exception as e:
        sys.stderr.write(f"[-] Error: {e}\n")
        sys.exit(1)

    log("Running analysis (aaa)...")
    r2.cmd('aaa')
    r2.cmd("fs imports")  # Switch to imports flag namespace.

    log("Fetching function list...")
    funcs = r2.cmdj('aflj') or []
    if not funcs:
        sys.stderr.write("[-] No functions found.\n")
        return

    total_funcs = len(funcs)
    log(f"Processing {total_funcs} functions...")

    output_data = {
        "metadata": {
            "filename": os.path.basename(filename),
            "total_functions": total_funcs,
        },
        "functions": [],
    }

    flag_cache = {}

    for count, f in enumerate(funcs, 1):
        f_name = f.get('name', 'unknown')
        f_addr = f.get('offset')
        f_cc = f.get('cc', 0)

        func_entry = {
            "name": f_name,
            "addr": hex(f_addr) if f_addr is not None else None,
            "cc": f_cc,
            "api_calls": [],
            "internal_calls": [],
        }

        ops = r2.cmdj(f"pdfj @ {f_addr}")
        if ops and 'ops' in ops:
            for op in ops['ops']:
                # Lowercase normalization in case a future r2 version starts
                # emitting 'CALL' / 'UCALL' / etc.
                op_type = (op.get('type') or '').lower()
                if op_type not in ('call', 'ucall', 'rcall', 'ircall'):
                    continue

                target_name, target_addr = resolve_target(r2, op, flag_cache)
                final_target = (
                    target_name if target_name
                    else (hex(target_addr) if target_addr else "Unresolved")
                )

                call_obj = {
                    "offset": hex(op.get('offset', 0)),
                    "instruction": op.get('disasm', ''),
                    "target": final_target,
                }

                if target_name and is_import_name(target_name):
                    func_entry["api_calls"].append(call_obj)
                else:
                    func_entry["internal_calls"].append(call_obj)

        if func_entry["api_calls"] or func_entry["internal_calls"]:
            output_data["functions"].append(func_entry)

        if count % 20 == 0:
            sys.stderr.write(f"\r[+] Progress: {count}/{total_funcs}")

    sys.stderr.write("\n")
    json.dump(output_data, sys.stdout, indent=4 if pretty_print else None)
    sys.stdout.write("\n")


def main():
    parser = argparse.ArgumentParser(
        description="Robust Call Tracer (handles indirect IAT calls)",
    )
    parser.add_argument("binary", help="Path to binary file")
    parser.add_argument("--compact", action="store_true",
                        help="Emit compact JSON instead of indented output")
    args = parser.parse_args()

    if not os.path.exists(args.binary):
        sys.stderr.write("[-] File not found.\n")
        sys.exit(1)

    analyze_calls(args.binary, pretty_print=not args.compact)


if __name__ == "__main__":
    main()
