#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
------------------------------------------------------------------------------
Script Name:   r2-dissector.py
Description:   Deep binary dissection and visualization using Radare2.
               Modes:
                 1. JSON Analysis (default): metadata, entropy, raw bytes,
                    optional basic blocks / instructions.
                 2. Single graph (-g FUNC): CFG for a specific function.
                 3. Batch graphs (--graph-all): CFGs for every function.
                 4. Call graph (--call-graph): global call graph of the binary.

Author:        Generated by Google Gemini, Revised by Ricardo J. Rodríguez
Created:       2025-11-26
Version:       2.2

Requirements:  pip install r2pipe graphviz
               System required: Graphviz (`dot`) and radare2 in PATH.
------------------------------------------------------------------------------
"""

import r2pipe
import argparse
import sys
import math
import json
import os
import re

try:
    import graphviz
    HAS_GRAPHVIZ = True
except ImportError:
    HAS_GRAPHVIZ = False


def log(msg):
    sys.stderr.write(f"[+] {msg}\n")


def error(msg):
    sys.stderr.write(f"[-] {msg}\n")


def calculate_entropy(hex_string):
    if not hex_string:
        return 0.0
    try:
        data = bytes.fromhex(hex_string)
    except ValueError:
        return 0.0
    if not data:
        return 0.0
    length = len(data)
    counts = [0] * 256
    for byte in data:
        counts[byte] += 1
    entropy = 0.0
    for count in counts:
        if count == 0:
            continue
        p = count / length
        entropy -= p * math.log2(p)
    return entropy


def render_dot_to_pdf(dot_data, output_base_path):
    """Renders DOT data to PDF. Returns True on success."""
    if not HAS_GRAPHVIZ:
        error("Graphviz Python library missing. Install: pip install graphviz")
        sys.exit(1)

    if not dot_data or len(dot_data.strip()) < 10:
        log(f"Warning: not enough graph data for {os.path.basename(output_base_path)}. Skipping.")
        return False

    try:
        src = graphviz.Source(dot_data)
        file_path = src.render(filename=output_base_path, format='pdf', cleanup=True)
        log(f"Saved: {file_path}")
        return True
    except graphviz.backend.ExecutableNotFound:
        error("Graphviz system executable ('dot') not found in PATH.")
        sys.exit(1)
    except Exception as e:
        error(f"Failed to render graph {output_base_path}: {e}")
        return False


def generate_call_graph(r2, output_dir):
    log("Generating GLOBAL CALL GRAPH (this might take a while)...")
    dot_data = r2.cmd("agCd")
    output_path = os.path.join(output_dir, "global_call_graph")
    render_dot_to_pdf(dot_data, output_path)


def generate_function_graph(r2, func_target, output_dir, seek_needed=True):
    """Returns (ok, pdf_filename, display_name) so callers can build an index."""
    if seek_needed:
        log(f"Processing function graph: {func_target}")
        try:
            r2.cmd(f"s {func_target}")
            disasm_check = r2.cmdj("pdfj")
            if not disasm_check:
                error(f"Function '{func_target}' not found or invalid.")
                return False, None, func_target
            actual_func_name = disasm_check.get('name', func_target)
        except Exception as e:
            error(f"Could not seek to function {func_target}: {e}")
            return False, None, func_target
    else:
        actual_func_name = func_target

    safe_name = re.sub(r'[^\w\-_. ]', '_', actual_func_name)
    output_path = os.path.join(output_dir, f"cfg_{safe_name}")
    dot_data = r2.cmd("agfd")
    ok = render_dot_to_pdf(dot_data, output_path)
    return ok, (f"cfg_{safe_name}.pdf" if ok else None), actual_func_name


def write_gallery_index(output_dir, entries, sample_name):
    """Write an HTML index linking to every CFG PDF. `entries` is a list of
    dicts with keys {pdf, name, cc, size}. Sorted by CC descending so the
    juiciest functions surface first."""
    if not entries:
        return

    entries = sorted(entries, key=lambda e: (-e.get("cc", 0), e["name"]))
    rows = []
    for e in entries:
        rows.append(
            f'<tr><td>{e["name"]}</td>'
            f'<td>{e.get("cc", 0)}</td>'
            f'<td>{e.get("size", 0)}</td>'
            f'<td><a href="{e["pdf"]}" target="_blank">view CFG</a></td></tr>'
        )

    html = f"""<!doctype html>
<html><head><meta charset="utf-8"><title>BinTopsy CFG Gallery — {sample_name}</title>
<style>
 body {{ font-family: -apple-system, sans-serif; margin: 2rem; }}
 h1 {{ font-size: 1.4rem; }}
 table {{ border-collapse: collapse; width: 100%; }}
 th, td {{ padding: 6px 12px; border-bottom: 1px solid #ddd; text-align: left; }}
 th {{ background: #f4f4f4; }}
 tr:hover {{ background: #fffbe6; }}
 .meta {{ color: #666; font-size: 0.9rem; }}
</style></head>
<body>
<h1>CFG Gallery — {sample_name}</h1>
<p class="meta">{len(entries)} functions, sorted by cyclomatic complexity (descending).</p>
<table>
<thead><tr><th>Function</th><th>CC</th><th>Size (bytes)</th><th>Graph</th></tr></thead>
<tbody>
{''.join(rows)}
</tbody></table>
</body></html>"""

    index_path = os.path.join(output_dir, "index.html")
    with open(index_path, 'w') as f:
        f.write(html)
    log(f"Gallery index: {index_path}")


def analyze_binary(filename, args):
    log(f"Opening radare2 session for: {filename}")
    try:
        r2 = r2pipe.open(filename, flags=['-2'])
    except Exception as e:
        error(f"Error opening file: {e}")
        sys.exit(1)

    log("Running deep analysis (aaa)...")
    r2.cmd('aaa')

    if args.graph or args.graph_all or args.call_graph:
        try:
            os.makedirs(args.output_dir, exist_ok=True)
            log(f"Graph output directory: {os.path.abspath(args.output_dir)}")
        except OSError as e:
            error(f"Could not create output directory: {e}")
            sys.exit(1)

    # MODE 1: Global call graph
    if args.call_graph:
        generate_call_graph(r2, args.output_dir)
        if not args.graph_all:
            return

    # MODE 2: Batch CFGs for every function
    if args.graph_all:
        log("Fetching function list for batch generation...")
        funcs = r2.cmdj('aflj')
        if not funcs:
            error("No functions found to graph.")
            return

        log(f"Starting batch generation for {len(funcs)} functions. Grab a coffee.")
        gallery = []
        for i, f in enumerate(funcs, 1):
            f_addr = f.get('offset')
            f_name = f.get('name', 'unknown')
            r2.cmd(f"s {f_addr}")
            ok, pdf, name = generate_function_graph(r2, f_name, args.output_dir,
                                                    seek_needed=False)
            if ok:
                gallery.append({
                    "pdf": pdf,
                    "name": name,
                    "cc": f.get("cc", 0),
                    "size": f.get("size", 0),
                })
            if i % 10 == 0:
                sys.stderr.write(f"[{i}/{len(funcs)}]\r")
        log(f"Batch complete. {len(funcs)} graphs attempted, {len(gallery)} succeeded.")
        write_gallery_index(args.output_dir, gallery, os.path.basename(filename))
        return

    # MODE 3: Single function CFG
    if args.graph:
        generate_function_graph(r2, args.graph, args.output_dir)
        return

    # === DEFAULT MODE: JSON analysis ===
    log("Fetching function list for JSON output...")
    funcs = r2.cmdj('aflj') or []

    if not funcs:
        json.dump({"metadata": {"file": filename}, "functions": []},
                  sys.stdout, indent=4)
        sys.stdout.write("\n")
        return

    log(f"Processing {len(funcs)} functions for JSON...")
    output_data = {
        "metadata": {
            "filename": os.path.basename(filename),
            "filepath": os.path.abspath(filename),
            "total_functions": len(funcs),
        },
        "functions": [],
    }

    for i, f in enumerate(funcs):
        f_addr = f.get('offset', 0)
        f_size = f.get('size', 0)
        f_name = f.get('name', 'unknown')
        r2.cmd(f"s {f_addr}")

        hex_dump = r2.cmd(f"p8 {f_size}").strip()
        entropy_val = calculate_entropy(hex_dump)

        func_obj = {
            "name": f_name,
            "address": f_addr,
            "address_hex": hex(f_addr),
            "size": f_size,
            "entropy": round(entropy_val, 5),
            "raw_bytes": hex_dump,
        }

        if args.blocks:
            blocks_raw = r2.cmdj('afbj')
            func_obj["basic_blocks"] = blocks_raw if blocks_raw else []

        if args.instructions:
            ops_raw = r2.cmdj('pdfj')
            func_obj["instructions"] = ops_raw['ops'] if (ops_raw and 'ops' in ops_raw) else []

        output_data["functions"].append(func_obj)
        if i % 50 == 0:
            sys.stderr.write(".")

    sys.stderr.write("\n")
    json.dump(output_data, sys.stdout, indent=4)
    sys.stdout.write("\n")


def main():
    parser = argparse.ArgumentParser(description="Radare2 Binary Dissector & Visualizer")
    parser.add_argument("binary", help="Path to binary file")

    parser.add_argument("--blocks", action="store_true",
                        help="Include basic blocks in JSON output")
    parser.add_argument("--instructions", action="store_true",
                        help="Include disassembly in JSON output")

    graph_group = parser.add_argument_group('Visualization options')
    graph_group.add_argument("-g", "--graph", metavar="FUNCTION",
                             help="Generate CFG PDF for a specific function.")
    graph_group.add_argument("--graph-all", action="store_true",
                             help="Generate CFG PDFs for ALL functions (slow & heavy).")
    graph_group.add_argument("--call-graph", action="store_true",
                             help="Generate the global call graph of the binary.")
    graph_group.add_argument("-od", "--output-dir", default="r2_graphs",
                             help="Directory to save generated graphs (default: r2_graphs)")

    args = parser.parse_args()

    if not os.path.exists(args.binary):
        error(f"File not found: {args.binary}")
        sys.exit(1)

    analyze_binary(args.binary, args)


if __name__ == "__main__":
    main()
