#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
------------------------------------------------------------------------------
Script Name:   r2-xref-grapher.py
Description:   Finds every function that calls a given API/import, prints a
               summary table, and generates a CFG (PDF) per caller.
               Also supports `--list-imports` to enumerate all imports with
               their xref counts and the maximum cyclomatic complexity among
               their callers (a quick triage view).

               v1.5 changes:
                 - Major perf fix: the flag list is now fetched ONCE, not
                   once per import (was O(N^2) on big binaries).
                 - Exact-match by default for API names; use --partial for
                   substring matching (the old loose default produced false
                   positives like matching "Sleep" against "SleepEx").
                 - Outputs to PDF (was PNG).
                 - Cleaner logging on stderr.

Author:        Generated by Google Gemini, Revised by Ricardo J. Rodríguez
Created:       2025-11-26
Version:       1.5

Requirements:  pip install r2pipe graphviz
               System required: Graphviz (`dot`) and radare2 in PATH.
------------------------------------------------------------------------------
"""

import r2pipe
import argparse
import sys
import os
import re

try:
    import graphviz
    HAS_GRAPHVIZ = True
except ImportError:
    HAS_GRAPHVIZ = False

# --- ANSI colours ---
RED = "\033[91m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
CYAN = "\033[96m"
RESET = "\033[0m"


def log(msg):
    sys.stderr.write(f"[+] {msg}\n")


def error(msg):
    sys.stderr.write(f"[-] {msg}\n")


def get_function_cc(r2, func_addr):
    try:
        info = r2.cmdj(f"afij @ {func_addr}")
        if info:
            return info[0].get('cc', 0)
    except Exception:
        pass
    return 0


def build_flag_index(r2):
    """Returns {flag_name: offset} for every flag once."""
    flags = r2.cmdj("fj") or []
    return {f.get('name', ''): f.get('offset', 0) for f in flags}


def find_import_xrefs(r2, imp, flag_index):
    """
    Resolve an import to addresses and gather every call/jump xref into it.
    Uses PLT (ELF), VAddr (PE/IAT), and flag-name lookup as fallback strategies.
    """
    candidates = []

    if imp.get('plt'):
        candidates.append(imp['plt'])
    if imp.get('vaddr'):
        candidates.append(imp['vaddr'])

    name = imp.get('name', '')
    if name:
        for fname, offset in flag_index.items():
            if fname.endswith(f".{name}") or fname == f"imp.{name}":
                candidates.append(offset)

    candidates = [a for a in set(candidates) if a]

    callers = set()
    for addr in candidates:
        xrefs = r2.cmdj(f"axtj {addr}") or []
        for x in xrefs:
            if x.get('type', '') in ('c', 'C', 'j', 'J'):
                callers.add(x.get('from'))
    return list(callers)


def list_imports_with_stats(r2, flag_index):
    log("Fetching imports and computing deep usage stats...")

    imports = r2.cmdj('iij')
    if not imports:
        error("No imports found (statically linked, packed, or stripped?).")
        return

    libs = {}
    total_imports = len(imports)

    for idx, imp in enumerate(imports, 1):
        lib = imp.get('lib', 'UNKNOWN_LIB')
        name = imp.get('name', 'unknown')

        callers = find_import_xrefs(r2, imp, flag_index)
        max_cc = 0
        for caller_addr in callers:
            func_info = r2.cmdj(f"pdfj @ {caller_addr}")
            if func_info and 'addr' in func_info:
                cc = get_function_cc(r2, func_info['addr'])
                if cc > max_cc:
                    max_cc = cc

        libs.setdefault(lib, []).append({
            "name": name,
            "count": len(callers),
            "max_cc": max_cc,
        })

        if idx % 10 == 0:
            sys.stderr.write(f"\r[+] Analyzing: {idx}/{total_imports}")

    sys.stderr.write("\n")

    print(f"\n{'=' * 105}")
    print(f"{'LIBRARY':<15} | {'API NAME':<35} | {'CALLS':<6} | {'MAX CALLER CC':<15} | RISK")
    print('-' * 105)

    for lib, funcs in libs.items():
        funcs_sorted = sorted(funcs, key=lambda x: (x['max_cc'], x['count']), reverse=True)
        print(f"{CYAN}{lib:<15}{RESET} | {len(funcs)} imports")

        for f in funcs_sorted:
            risk = "-"
            row_color = RESET
            if f['count'] == 0:
                pass
            elif f['max_cc'] > 20:
                row_color, risk = RED, "HIGH COMPLEXITY"
            elif f['max_cc'] > 10:
                row_color, risk = YELLOW, "MEDIUM"
            elif f['count'] > 10:
                row_color, risk = YELLOW, "HEAVY USAGE"

            print(f"{row_color}{'':<15} | {f['name']:<35} | {f['count']:<6} | "
                  f"{f['max_cc']:<15} | {risk}{RESET}")
        print('-' * 105)


def render_dot_to_pdf(dot_data, output_path):
    if not HAS_GRAPHVIZ:
        error("Graphviz library missing.")
        sys.exit(1)
    if not dot_data or len(dot_data.strip()) < 10:
        return False
    try:
        graphviz.Source(dot_data).render(filename=output_path, format='pdf', cleanup=True)
        return True
    except Exception as e:
        error(f"Render failed for {output_path}: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(
        description="Generate CFGs for every function calling a specific API.",
    )
    parser.add_argument("binary", help="Path to binary file")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("api", nargs='?', help="Name of the API/import (exact, case-insensitive)")
    group.add_argument("-l", "--list-imports", action="store_true",
                       help="List imports with xref counts and max caller complexity.")
    parser.add_argument("--partial", action="store_true",
                        help="Substring match instead of exact match for the API name.")
    parser.add_argument("-o", "--output", default="xref_graphs", help="Output directory")
    args = parser.parse_args()

    if not os.path.exists(args.binary):
        error("File not found.")
        sys.exit(1)

    log(f"Opening binary: {args.binary}")
    try:
        r2 = r2pipe.open(args.binary, flags=['-2'])
        r2.cmd('aaa')
    except Exception as e:
        error(f"Error initializing r2: {e}")
        sys.exit(1)

    flag_index = build_flag_index(r2)

    if args.list_imports:
        list_imports_with_stats(r2, flag_index)
        return

    api_name = args.api
    log(f"Searching for functions using: '{api_name}' "
        f"({'partial' if args.partial else 'exact'} match)")

    def name_matches(candidate):
        if not candidate:
            return False
        if args.partial:
            return api_name.lower() in candidate.lower()
        return candidate.lower() == api_name.lower()

    dummy_imp = {'name': api_name, 'plt': 0, 'vaddr': 0}

    # Try to populate addresses from symbols / imports.
    found = False
    for s in (r2.cmdj('isj') or []):
        if name_matches(s.get('name', '')):
            dummy_imp['vaddr'] = s.get('vaddr')
            found = True
            break

    if not found:
        for i in (r2.cmdj('iij') or []):
            if name_matches(i.get('name', '')):
                dummy_imp['plt'] = i.get('plt')
                dummy_imp['vaddr'] = i.get('vaddr')
                found = True
                break

    callers = find_import_xrefs(r2, dummy_imp, flag_index)

    if not callers:
        error(f"No code references found for '{api_name}'.")
        return

    parent_functions = {}
    for caller_addr in callers:
        func_info = r2.cmdj(f"pdfj @ {caller_addr}")
        if func_info and 'name' in func_info:
            f_addr = func_info.get('addr')
            if f_addr not in parent_functions:
                parent_functions[f_addr] = {
                    'name': func_info['name'],
                    'cc': get_function_cc(r2, f_addr),
                }

    print(f"\n[+] Found {len(parent_functions)} unique callers for '{api_name}':")
    print(f"{'FUNCTION NAME':<40} | COMPLEXITY (CC)")
    print('-' * 60)
    for info in parent_functions.values():
        cc_color = RED if info['cc'] > 15 else GREEN
        print(f"{info['name']:<40} | {cc_color}{info['cc']}{RESET}")
    print('-' * 60)

    os.makedirs(args.output, exist_ok=True)
    log(f"Generating graphs in '{args.output}'...")

    for f_addr, info in parent_functions.items():
        safe_fname = re.sub(r'[^\w\-_. ]', '_', info['name'])
        safe_api = re.sub(r'[^\w\-_. ]', '_', api_name)
        output_name = os.path.join(
            args.output,
            f"call_{safe_api}_in_{safe_fname}_CC{info['cc']}",
        )
        r2.cmd(f"s {f_addr}")
        dot_data = r2.cmd("agfd")
        render_dot_to_pdf(dot_data, output_name)


if __name__ == "__main__":
    main()
