#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
------------------------------------------------------------------------------
Script Name:   sda-hashes.py
Description:   Parses the JSON output from 'r2_json_dissector', decodes the 
               'raw_bytes' of each function, and computes fuzzy hashes.
               Supports ssdeep and TLSH (configurable via CLI).

Author:        Generated by Google Gemini, Revised by Ricardo J. Rodríguez
Created:       2025-11-23
Version:       2.0

Requirements:  pip install ssdeep python-tlsh
------------------------------------------------------------------------------
"""

import json
import argparse
import sys
import os

# --- Dynamic Import with Flags ---
try:
    import ssdeep
    HAS_SSDEEP = True
except ImportError:
    HAS_SSDEEP = False

try:
    import tlsh
    HAS_TLSH = True
except ImportError:
    HAS_TLSH = False

def enrich_json(input_file, output_file=None, use_ssdeep=True, use_tlsh=True):
    print(f"[+] Loading JSON file: {input_file}")
    
    try:
        with open(input_file, 'r') as f:
            data = json.load(f)
    except Exception as e:
        print(f"[-] Error reading JSON file: {e}")
        sys.exit(1)

    # Validate JSON structure
    if "functions" not in data:
        print("[-] Invalid JSON format. Key 'functions' is missing.")
        sys.exit(1)

    functions = data["functions"]
    total = len(functions)
    
    print(f"[+] Processing {total} functions...")
    print(f"    |__ ssdeep enabled: {use_ssdeep}")
    print(f"    |__ TLSH enabled:   {use_tlsh}")

    processed_count = 0
    skipped_count = 0

    for i, func in enumerate(functions):
        raw_hex = func.get("raw_bytes", "")
        
        # Skip if no raw bytes are present
        if not raw_hex:
            func["fuzzy_hashes"] = {"error": "No raw bytes available"}
            skipped_count += 1
            continue

        try:
            # Convert Hex String back to actual Bytes
            byte_data = bytes.fromhex(raw_hex)
            
            # Dictionary to store results for this function
            hashes = {}

            # --- SSDEEP Computation ---
            if use_ssdeep:
                try:
                    # ssdeep works on almost any input size
                    hashes['ssdeep'] = ssdeep.hash(byte_data)
                except Exception as e:
                    hashes['ssdeep'] = f"Error: {str(e)}"

            # --- TLSH Computation ---
            if use_tlsh:
                # TLSH requires a minimum data length (usually >= 50 bytes) 
                # and a minimum amount of complexity/entropy.
                if len(byte_data) >= 50:
                    try:
                        hashes['tlsh'] = tlsh.hash(byte_data)
                    except Exception:
                        # Occurs if data is too repetitive (low entropy)
                        hashes['tlsh'] = "T_NULL (Complexity too low)"
                else:
                    hashes['tlsh'] = "T_TOO_SHORT (<50 bytes)"

            # Update the function object
            # If 'fuzzy_hashes' already exists (from a previous run), we update it.
            if "fuzzy_hashes" not in func:
                func["fuzzy_hashes"] = {}
            
            func["fuzzy_hashes"].update(hashes)
            
            processed_count += 1

        except Exception as e:
            print(f"[-] Unexpected error processing function '{func.get('name')}': {e}")
            skipped_count += 1

        # Simple progress indicator
        if i % 100 == 0:
            sys.stdout.write(f"\r[+] Progress: {i}/{total}")
            sys.stdout.flush()

    print(f"\n[+] Processing complete.")
    print(f"    |__ Functions Enriched: {processed_count}")

    # Determine output filename
    if not output_file:
        base, ext = os.path.splitext(input_file)
        output_file = f"{base}_enriched{ext}"

    print(f"[+] Saving enriched data to: {output_file}")
    try:
        with open(output_file, 'w') as f:
            json.dump(data, f, indent=4)
    except Exception as e:
        print(f"[-] Error saving file: {e}")

def main():
    parser = argparse.ArgumentParser(description="Enrich r2-dissect JSON with fuzzy hashes.")
    
    parser.add_argument("input", help="Input JSON file")
    parser.add_argument("-o", "--output", help="Output JSON filename (Optional)")
    
    # Flags for hashing algorithms
    parser.add_argument("--ssdeep", action="store_true", help="Calculate ssdeep hash")
    parser.add_argument("--tlsh", action="store_true", help="Calculate TLSH hash")
    
    args = parser.parse_args()

    # --- Logic: If no specific flag is set, enable BOTH by default ---
    do_ssdeep = args.ssdeep
    do_tlsh = args.tlsh

    if not do_ssdeep and not do_tlsh:
        do_ssdeep = True
        do_tlsh = True

    # --- Dependency Checks ---
    if do_ssdeep and not HAS_SSDEEP:
        print("[-] Error: You requested --ssdeep, but the library is not installed.")
        print("    Install: pip install ssdeep (and ensure libfuzzy-dev is on your system)")
        sys.exit(1)

    if do_tlsh and not HAS_TLSH:
        print("[-] Error: You requested --tlsh, but the library is not installed.")
        print("    Install: pip install python-tlsh")
        sys.exit(1)

    if not os.path.exists(args.input):
        print(f"[-] Input file not found: {args.input}")
        sys.exit(1)

    enrich_json(args.input, args.output, use_ssdeep=do_ssdeep, use_tlsh=do_tlsh)

if __name__ == "__main__":
    main()
