#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
------------------------------------------------------------------------------
Script Name:   sda-hashes.py
Description:   Parses the JSON output from `r2-dissector.py`, decodes the
               `raw_bytes` of each function, and computes fuzzy hashes
               (ssdeep and/or TLSH) so that callers can compare or cluster
               functions across binaries.

               v2.1 changes:
                 - Progress and status messages go to stderr (the previous
                   stdout writes interfered with `--output -` style usage).
                 - Replaced bare except with specific exceptions.

Author:        Generated by Google Gemini, Revised by Ricardo J. Rodríguez
Created:       2025-11-23
Version:       2.1

Requirements:  pip install ssdeep python-tlsh
               System required: libfuzzy-dev (Linux) or `ssdeep` (Homebrew).
------------------------------------------------------------------------------
"""

import json
import argparse
import sys
import os

try:
    import ssdeep
    HAS_SSDEEP = True
except ImportError:
    HAS_SSDEEP = False

try:
    import tlsh
    HAS_TLSH = True
except ImportError:
    HAS_TLSH = False


def log(msg):
    sys.stderr.write(f"[+] {msg}\n")


def error(msg):
    sys.stderr.write(f"[-] {msg}\n")


def enrich_json(input_file, output_file=None, use_ssdeep=True, use_tlsh=True):
    log(f"Loading JSON file: {input_file}")

    try:
        with open(input_file, 'r') as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError) as e:
        error(f"Error reading JSON file: {e}")
        sys.exit(1)

    if "functions" not in data:
        error("Invalid JSON format. Key 'functions' is missing.")
        sys.exit(1)

    functions = data["functions"]
    total = len(functions)

    log(f"Processing {total} functions  |  ssdeep={use_ssdeep}  tlsh={use_tlsh}")

    processed_count = 0
    skipped_count = 0

    for i, func in enumerate(functions):
        raw_hex = func.get("raw_bytes", "")

        if not raw_hex:
            func["fuzzy_hashes"] = {"error": "No raw bytes available"}
            skipped_count += 1
            continue

        try:
            byte_data = bytes.fromhex(raw_hex)
        except ValueError as e:
            error(f"Bad hex for function '{func.get('name')}': {e}")
            skipped_count += 1
            continue

        hashes = func.get("fuzzy_hashes", {})

        if use_ssdeep:
            try:
                hashes['ssdeep'] = ssdeep.hash(byte_data)
            except Exception as e:
                hashes['ssdeep'] = f"Error: {e}"

        if use_tlsh:
            if len(byte_data) >= 50:
                try:
                    hashes['tlsh'] = tlsh.hash(byte_data)
                except ValueError:
                    hashes['tlsh'] = "T_NULL (Complexity too low)"
            else:
                hashes['tlsh'] = "T_TOO_SHORT (<50 bytes)"

        func["fuzzy_hashes"] = hashes
        processed_count += 1

        if i % 100 == 0:
            sys.stderr.write(f"\r[+] Progress: {i}/{total}")

    sys.stderr.write("\n")
    log(f"Processed: {processed_count}  |  Skipped: {skipped_count}")

    if not output_file:
        base, ext = os.path.splitext(input_file)
        output_file = f"{base}_enriched{ext}"

    log(f"Saving enriched data to: {output_file}")
    try:
        with open(output_file, 'w') as f:
            json.dump(data, f, indent=4)
    except OSError as e:
        error(f"Error saving file: {e}")
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(description="Enrich r2-dissector JSON with fuzzy hashes.")
    parser.add_argument("input", help="Input JSON file")
    parser.add_argument("-o", "--output", help="Output JSON filename (default: <input>_enriched.json)")
    parser.add_argument("--ssdeep", action="store_true", help="Calculate ssdeep hash")
    parser.add_argument("--tlsh", action="store_true", help="Calculate TLSH hash")
    args = parser.parse_args()

    do_ssdeep = args.ssdeep
    do_tlsh = args.tlsh
    if not do_ssdeep and not do_tlsh:
        do_ssdeep = do_tlsh = True

    if do_ssdeep and not HAS_SSDEEP:
        error("--ssdeep requested but the library is not installed.")
        error("Install: pip install ssdeep  (and ensure libfuzzy-dev is on your system)")
        sys.exit(1)

    if do_tlsh and not HAS_TLSH:
        error("--tlsh requested but the library is not installed.")
        error("Install: pip install python-tlsh")
        sys.exit(1)

    if not os.path.exists(args.input):
        error(f"Input file not found: {args.input}")
        sys.exit(1)

    enrich_json(args.input, args.output, use_ssdeep=do_ssdeep, use_tlsh=do_tlsh)


if __name__ == "__main__":
    main()
