#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
------------------------------------------------------------------------------
Script Name:   vt-folder-scan.py
Description:   Scans a directory, hashes the files (SHA256), and checks them 
               against the VirusTotal API. Supports exclusions and rate limiting.

Author:        Generated by Google Gemini, Revised by Ricardo J. Rodríguez
Created:       2025-11-23
Version:       2.0

Requirements:  pip install requests python-dotenv
------------------------------------------------------------------------------
"""
import os
import sys
import time
import hashlib
import argparse
import requests
from dotenv import load_dotenv

# ANSI Color codes for terminal output
GREEN = "\033[92m"
RED = "\033[91m"
YELLOW = "\033[93m"
CYAN = "\033[96m"
RESET = "\033[0m"

VT_API_URL = "https://www.virustotal.com/api/v3/files/"

def calculate_sha256(filepath):
    """Calculates the SHA256 hash of a file efficiently."""
    sha256_hash = hashlib.sha256()
    try:
        with open(filepath, "rb") as f:
            for byte_block in iter(lambda: f.read(4096), b""):
                sha256_hash.update(byte_block)
        return sha256_hash.hexdigest()
    except Exception as e:
        print(f"{RED}[-] Error reading file {filepath}: {e}{RESET}")
        return None

def check_virustotal(file_hash, api_key):
    """Queries VirusTotal API v3 for the file hash."""
    headers = {
        "x-apikey": api_key
    }
    try:
        response = requests.get(VT_API_URL + file_hash, headers=headers)
        
        if response.status_code == 200:
            return response.json()
        elif response.status_code == 404:
            return "NOT_FOUND"
        elif response.status_code == 401:
            print(f"{RED}[!] Error: Invalid or Expired API Key.{RESET}")
            sys.exit(1)
        elif response.status_code == 429:
            print(f"{YELLOW}[!] Quota Exceeded. Waiting 60 seconds...{RESET}")
            time.sleep(60)
            return check_virustotal(file_hash, api_key) # Retry
        else:
            print(f"{RED}[-] API Error: {response.status_code}{RESET}")
            return None
    except Exception as e:
        print(f"{RED}[-] Network Error: {e}{RESET}")
        return None

def print_report(filename, result):
    """Parses and prints the JSON result in a readable format."""
    if result == "NOT_FOUND":
        print(f"{CYAN}[?] {filename}{RESET}")
        print(f"    |_ Status: {YELLOW}Unknown to VirusTotal (File never uploaded){RESET}")
        return

    if not result:
        return

    try:
        attributes = result.get('data', {}).get('attributes', {})
        stats = attributes.get('last_analysis_stats', {})
        
        malicious = stats.get('malicious', 0)
        suspicious = stats.get('suspicious', 0)
        
        total_engines = sum(stats.values())
        
        # Determine Color based on detection
        if malicious > 0:
            status_color = RED
            verdict = "MALICIOUS"
        elif suspicious > 0:
            status_color = YELLOW
            verdict = "SUSPICIOUS"
        else:
            status_color = GREEN
            verdict = "CLEAN"

        print(f"{status_color}[*] {filename}{RESET}")
        print(f"    |_ Verdict: {status_color}{verdict}{RESET} ({malicious}/{total_engines} engines)")
        print(f"    |_ Type: {attributes.get('type_description', 'Unknown')}")
        
        if malicious > 0:
            results = attributes.get('last_analysis_results', {})
            detected_by = [k for k, v in results.items() if v['category'] == 'malicious']
            # Show only top 5 to avoid clutter
            print(f"    |_ Detected by: {', '.join(detected_by[:5])}...")
            
        print(f"    |_ Link: https://www.virustotal.com/gui/file/{result['data']['id']}")

    except Exception as e:
        print(f"{RED}[-] Error parsing report for {filename}: {e}{RESET}")

def main():
    parser = argparse.ArgumentParser(description="VirusTotal Folder Scanner (Hash Check)")
    parser.add_argument("folder", help="Path to the folder to scan")
    parser.add_argument("--avoid", nargs='+', default=[], 
                        help="List of extensions to exclude (e.g. .txt .log .png)")
    parser.add_argument("--premium", action="store_true", 
                        help="Enable if you have a Premium Key (No rate limit sleep)")
    
    args = parser.parse_args()

    # --- SECRETS LOADING ---
    # 1. Load from secrets.env file if it exists
    load_dotenv("secrets.env")
    
    # 2. Get variable from environment
    api_key = os.getenv("VT_API_KEY")
    
    if not api_key:
        print(f"{RED}[!] Error: VT_API_KEY not found in 'secrets.env' or environment variables.{RESET}")
        print(f"{YELLOW}    Please create a 'secrets.env' file containing: VT_API_KEY=your_key{RESET}")
        sys.exit(1)
    # -----------------------

    if not os.path.isdir(args.folder):
        print(f"{RED}[!] Error: Directory not found.{RESET}")
        sys.exit(1)

    # --- PROCESSING EXCLUSIONS ---
    # Normalize exclusions: lowercase and ensure they start with '.'
    excluded_exts = []
    for ext in args.avoid:
        ext = ext.lower()
        if not ext.startswith('.'):
            ext = '.' + ext
        excluded_exts.append(ext)
    
    if excluded_exts:
        print(f"{YELLOW}[i] Ignoring files with extensions: {', '.join(excluded_exts)}{RESET}")

    # --- FILE DISCOVERY ---
    files_to_scan = []
    skipped_count = 0

    for root, _, files in os.walk(args.folder):
        for file in files:
            # Check if file matches exclusion list
            if any(file.lower().endswith(ext) for ext in excluded_exts):
                skipped_count += 1
                continue
            
            files_to_scan.append(os.path.join(root, file))

    print(f"--- Scanning {len(files_to_scan)} files in: {args.folder} (Skipped: {skipped_count}) ---")
    
    # --- SCAN LOOP ---
    for i, filepath in enumerate(files_to_scan):
        filename = os.path.basename(filepath)
        
        # 1. Calculate Hash
        file_hash = calculate_sha256(filepath)
        if not file_hash:
            continue

        # 2. Query API
        result = check_virustotal(file_hash, api_key)
        
        # 3. Print Report
        print_report(filename, result)

        # 4. Rate Limiting (4 requests/minute for Free accounts)
        if not args.premium and i < len(files_to_scan) - 1:
            # Optional: simple countdown to show activity
            # print(f"    ...waiting 15s...", end='\r')
            time.sleep(15) 

if __name__ == "__main__":
    main()
