#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
------------------------------------------------------------------------------
Script Name:   vt-folder-scan.py
Description:   Scans a directory, hashes each file (SHA256), and queries the
               VirusTotal v3 API for known reports. The script never uploads
               file content; only hashes leave the host.

               v2.1 changes:
                 - Added request timeouts (no more silent hangs).
                 - 429 backoff is iterative with a max retry count.
                 - Optional --output to dump structured JSON results.
                 - Skips files larger than --max-size to save quota.

Author:        Generated by Google Gemini, Revised by Ricardo J. Rodríguez
Created:       2025-11-23
Version:       2.1

Requirements:  pip install requests python-dotenv
------------------------------------------------------------------------------
"""
import os
import sys
import time
import json
import hashlib
import argparse
import requests
from dotenv import load_dotenv

# ANSI Color codes for terminal output
GREEN = "\033[92m"
RED = "\033[91m"
YELLOW = "\033[93m"
CYAN = "\033[96m"
RESET = "\033[0m"

VT_API_URL = "https://www.virustotal.com/api/v3/files/"
DEFAULT_TIMEOUT = 30           # seconds for each HTTP request
MAX_429_RETRIES = 3            # how many times to back off on quota errors
FREE_TIER_SLEEP = 15           # seconds between requests on the free tier


def calculate_sha256(filepath):
    """SHA256 of a file, streamed in 64KB blocks."""
    sha256_hash = hashlib.sha256()
    try:
        with open(filepath, "rb") as f:
            for byte_block in iter(lambda: f.read(65536), b""):
                sha256_hash.update(byte_block)
        return sha256_hash.hexdigest()
    except OSError as e:
        print(f"{RED}[-] Error reading file {filepath}: {e}{RESET}", file=sys.stderr)
        return None


def check_virustotal(file_hash, api_key, timeout=DEFAULT_TIMEOUT):
    """Queries VirusTotal API v3 for the given hash. Returns dict, 'NOT_FOUND', or None."""
    headers = {"x-apikey": api_key}
    url = VT_API_URL + file_hash

    for attempt in range(MAX_429_RETRIES + 1):
        try:
            response = requests.get(url, headers=headers, timeout=timeout)
        except requests.Timeout:
            print(f"{RED}[-] Timeout querying VT for {file_hash[:12]}...{RESET}",
                  file=sys.stderr)
            return None
        except requests.RequestException as e:
            print(f"{RED}[-] Network Error: {e}{RESET}", file=sys.stderr)
            return None

        if response.status_code == 200:
            return response.json()
        if response.status_code == 404:
            return "NOT_FOUND"
        if response.status_code == 401:
            print(f"{RED}[!] Error: Invalid or Expired API Key.{RESET}", file=sys.stderr)
            sys.exit(1)
        if response.status_code == 429:
            wait = 60 * (attempt + 1)
            print(f"{YELLOW}[!] Quota exceeded (attempt {attempt + 1}/{MAX_429_RETRIES + 1}). "
                  f"Waiting {wait}s...{RESET}", file=sys.stderr)
            time.sleep(wait)
            continue

        print(f"{RED}[-] API Error: {response.status_code}{RESET}", file=sys.stderr)
        return None

    print(f"{RED}[-] Giving up after {MAX_429_RETRIES} retries on quota errors.{RESET}",
          file=sys.stderr)
    return None


def summarise(filename, file_hash, result):
    """Builds the structured record + prints the human-readable report."""
    record = {"filename": filename, "sha256": file_hash}

    if result == "NOT_FOUND":
        print(f"{CYAN}[?] {filename}{RESET}")
        print(f"    |_ Status: {YELLOW}Unknown to VirusTotal{RESET}")
        record["verdict"] = "UNKNOWN"
        return record

    if not result:
        record["verdict"] = "ERROR"
        return record

    try:
        attributes = result.get('data', {}).get('attributes', {})
        stats = attributes.get('last_analysis_stats', {})
        malicious = stats.get('malicious', 0)
        suspicious = stats.get('suspicious', 0)
        total_engines = sum(stats.values())

        if malicious > 0:
            color, verdict = RED, "MALICIOUS"
        elif suspicious > 0:
            color, verdict = YELLOW, "SUSPICIOUS"
        else:
            color, verdict = GREEN, "CLEAN"

        print(f"{color}[*] {filename}{RESET}")
        print(f"    |_ Verdict: {color}{verdict}{RESET} ({malicious}/{total_engines} engines)")
        print(f"    |_ Type: {attributes.get('type_description', 'Unknown')}")

        record.update({
            "verdict": verdict,
            "malicious": malicious,
            "suspicious": suspicious,
            "total_engines": total_engines,
            "type": attributes.get('type_description'),
            "vt_link": f"https://www.virustotal.com/gui/file/{result['data']['id']}",
        })

        if malicious > 0:
            results = attributes.get('last_analysis_results', {})
            detected_by = [k for k, v in results.items() if v['category'] == 'malicious']
            print(f"    |_ Detected by: {', '.join(detected_by[:5])}"
                  + (", ..." if len(detected_by) > 5 else ""))
            record["detected_by"] = detected_by

        print(f"    |_ Link: {record['vt_link']}")

    except (KeyError, TypeError) as e:
        print(f"{RED}[-] Error parsing report for {filename}: {e}{RESET}", file=sys.stderr)
        record["verdict"] = "PARSE_ERROR"

    return record


def main():
    parser = argparse.ArgumentParser(description="VirusTotal Folder Scanner (Hash Check)")
    parser.add_argument("folder", help="Path to the folder to scan")
    parser.add_argument("--avoid", nargs='+', default=[],
                        help="Extensions to exclude (e.g. .txt .log .png)")
    parser.add_argument("--premium", action="store_true",
                        help="Disable the 15s rate limiter (premium / paid keys)")
    parser.add_argument("--max-size", type=int, default=0,
                        help="Skip files larger than N bytes (0 = no limit)")
    parser.add_argument("-o", "--output", help="Dump structured results to a JSON file")
    parser.add_argument("--timeout", type=int, default=DEFAULT_TIMEOUT,
                        help=f"HTTP timeout in seconds (default: {DEFAULT_TIMEOUT})")
    args = parser.parse_args()

    # --- SECRETS LOADING ---
    load_dotenv("secrets.env")
    api_key = os.getenv("VT_API_KEY")

    if not api_key:
        print(f"{RED}[!] Error: VT_API_KEY not found in 'secrets.env' or environment.{RESET}",
              file=sys.stderr)
        print(f"{YELLOW}    Create a 'secrets.env' file with: VT_API_KEY=your_key{RESET}",
              file=sys.stderr)
        sys.exit(1)

    if not os.path.isdir(args.folder):
        print(f"{RED}[!] Error: Directory not found.{RESET}", file=sys.stderr)
        sys.exit(1)

    excluded_exts = []
    for ext in args.avoid:
        ext = ext.lower()
        if not ext.startswith('.'):
            ext = '.' + ext
        excluded_exts.append(ext)

    if excluded_exts:
        print(f"{YELLOW}[i] Ignoring extensions: {', '.join(excluded_exts)}{RESET}")

    # --- FILE DISCOVERY ---
    files_to_scan = []
    skipped_count = 0

    for root, _, files in os.walk(args.folder):
        for file in files:
            if any(file.lower().endswith(ext) for ext in excluded_exts):
                skipped_count += 1
                continue
            full_path = os.path.join(root, file)
            if args.max_size > 0:
                try:
                    if os.path.getsize(full_path) > args.max_size:
                        skipped_count += 1
                        continue
                except OSError:
                    pass
            files_to_scan.append(full_path)

    print(f"--- Scanning {len(files_to_scan)} files in: {args.folder} (Skipped: {skipped_count}) ---")

    results = []

    for i, filepath in enumerate(files_to_scan):
        filename = os.path.basename(filepath)

        file_hash = calculate_sha256(filepath)
        if not file_hash:
            continue

        result = check_virustotal(file_hash, api_key, timeout=args.timeout)
        record = summarise(filename, file_hash, result)
        results.append(record)

        if not args.premium and i < len(files_to_scan) - 1:
            time.sleep(FREE_TIER_SLEEP)

    if args.output:
        try:
            with open(args.output, 'w') as f:
                json.dump(results, f, indent=2)
            print(f"\n[+] Wrote {len(results)} records to {args.output}")
        except OSError as e:
            print(f"{RED}[-] Could not write {args.output}: {e}{RESET}", file=sys.stderr)


if __name__ == "__main__":
    main()
