
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
------------------------------------------------------------------------------
Script Name:   yara-chunk-scanner.py
Description:   Recursively scans files or directories using YARA rules. 
               Splits files into pages (chunks) to analyze large dumps efficiently.

Author:        Generated by Google Gemini, Revised by Ricardo J. Rodríguez
Created:       2025-11-23
Version:       3.0

Requirements:  pip install yara-python
------------------------------------------------------------------------------
"""
import argparse
import os
import sys
import yara

def compile_rules(path):
    """
    Compiles YARA rules from a single file OR a directory (recursively).
    """
    rules_to_compile = {}

    if os.path.isfile(path):
        rules_to_compile['main'] = path
    elif os.path.isdir(path):
        print(f"[+] Loading rules from directory: {path}")
        for root, _, files in os.walk(path):
            for file in files:
                if file.lower().endswith(('.yar', '.yara')):
                    full_path = os.path.join(root, file)
                    # Sanitize filename to create a valid YARA namespace
                    namespace = file.replace(" ", "_").replace(".", "_")
                    rules_to_compile[namespace] = full_path
    else:
        print(f"[-] Error: Rule path does not exist: {path}")
        sys.exit(1)

    if not rules_to_compile:
        print("[-] Error: No .yar/.yara files found in the specified path.")
        sys.exit(1)

    print(f"[+] Compiling {len(rules_to_compile)} rule files...")
    
    try:
        rules = yara.compile(filepaths=rules_to_compile)
        return rules
    except yara.SyntaxError as e:
        print(f"[-] SYNTAX ERROR in rules: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"[-] Error compiling rules: {e}")
        sys.exit(1)

def print_match(filename, global_offset, match_obj):
    """
    Prints the match report with the filename.
    """
    tags = f" [{', '.join(match_obj.tags)}]" if match_obj.tags else ""
    source_rule_file = match_obj.namespace if match_obj.namespace != 'main' else 'Single File'
    
    print(f"\n[!] MATCH FOUND in: {filename}")
    print(f"    Rule: {match_obj.rule}{tags}")
    print(f"    Rule Source: {source_rule_file}") 
    
    for s in match_obj.strings:
        rel_offset, string_id, string_val = s
        abs_offset = global_offset + rel_offset
        
        try:
            val_str = string_val.decode('utf-8', errors='replace')
        except:
            val_str = str(string_val)
            
        if len(val_str) > 50:
            val_str = val_str[:47] + "..."

        print(f"    |__ Offset: 0x{abs_offset:08x} | Str: {string_id} | Data: {val_str}")

def scan_file(filepath, rules, page_size):
    """
    Scans a single file in chunks. Returns the number of matches found.
    """
    chunk_count = 0
    matches_in_file = 0

    try:
        filesize = os.path.getsize(filepath)
        if filesize == 0:
            return 0

        with open(filepath, 'rb') as f:
            while True:
                current_global_offset = chunk_count * page_size
                chunk = f.read(page_size)
                if not chunk:
                    break
                
                try:
                    matches = rules.match(data=chunk)
                    if matches:
                        for m in matches:
                            matches_in_file += 1
                            print_match(filepath, current_global_offset, m)
                except Exception as e:
                    # Suppress small read errors to keep output clean, or print if critical
                    pass

                chunk_count += 1
                
    except PermissionError:
        print(f"[-] Permission Denied: {filepath}")
    except Exception as e:
        print(f"[-] Error scanning {filepath}: {e}")

    return matches_in_file

def main():
    parser = argparse.ArgumentParser(description="Recursive Chunk-based YARA Scanner")
    
    parser.add_argument("target", help="File OR Directory to analyze")
    parser.add_argument("rules", help="Path to a .yar file OR a directory of rules")
    parser.add_argument("-p", "--page-size", type=int, default=4096, 
                        help="Chunk/Page size in bytes (Default: 4096)")
    
    args = parser.parse_args()

    # 1. Compile Rules
    rules = compile_rules(args.rules)
    
    # 2. Identify Targets
    files_to_scan = []
    if os.path.isfile(args.target):
        files_to_scan.append(args.target)
    elif os.path.isdir(args.target):
        print(f"[+] Enumerating files in directory: {args.target}...")
        for root, _, files in os.walk(args.target):
            for file in files:
                files_to_scan.append(os.path.join(root, file))
    else:
        print(f"[-] Target not found: {args.target}")
        sys.exit(1)

    print(f"[+] Target(s) identified: {len(files_to_scan)}")
    print(f"[+] Page size: {args.page_size} bytes")
    print("=" * 60)

    # 3. Main Scan Loop
    total_matches = 0
    files_scanned = 0

    try:
        for file_path in files_to_scan:
            # Optional: Print progress for large directories
            # print(f"Scanning: {file_path}", end='\r') 
            
            matches = scan_file(file_path, rules, args.page_size)
            if matches > 0:
                total_matches += matches
                print("-" * 60) # Separator between files with matches
            
            files_scanned += 1

    except KeyboardInterrupt:
        print("\n[!] Analysis interrupted by user.")
        sys.exit(0)

    print("\n" + "=" * 60)
    print(f"[+] Finished.")
    print(f"[+] Files Scanned: {files_scanned}")
    print(f"[+] Total Detections: {total_matches}")

if __name__ == "__main__":
    main()
