#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
------------------------------------------------------------------------------
Script Name:   yara-chunk-scanner.py
Description:   Recursively scans files or directories using YARA rules.
               Splits files into pages (chunks) so massive dumps can be
               analyzed without loading them entirely into RAM.

               v3.1 changes:
                 - Compatible with yara-python >= 4.3 StringMatch API
                   (also keeps backward compatibility with the legacy
                   3-tuple format).
                 - Optional --overlap to catch matches that straddle the
                   boundary between two chunks (cross-chunk strings would
                   otherwise be silently missed).
                 - Surfaces YARA scan errors instead of swallowing them.

Author:        Generated by Google Gemini, Revised by Ricardo J. Rodríguez
Created:       2025-11-23
Version:       3.1

Requirements:  pip install yara-python
------------------------------------------------------------------------------
"""
import argparse
import os
import sys
import yara


def compile_rules(path):
    """Compiles YARA rules from a single file OR a directory (recursively)."""
    rules_to_compile = {}

    if os.path.isfile(path):
        rules_to_compile['main'] = path
    elif os.path.isdir(path):
        print(f"[+] Loading rules from directory: {path}")
        for root, _, files in os.walk(path):
            for file in files:
                if file.lower().endswith(('.yar', '.yara')):
                    full_path = os.path.join(root, file)
                    namespace = os.path.relpath(full_path, path).replace(os.sep, '_')
                    rules_to_compile[namespace] = full_path
    else:
        print(f"[-] Error: Rule path does not exist: {path}", file=sys.stderr)
        sys.exit(1)

    if not rules_to_compile:
        print("[-] Error: No .yar/.yara files found in the specified path.",
              file=sys.stderr)
        sys.exit(1)

    print(f"[+] Compiling {len(rules_to_compile)} rule files...")

    try:
        return yara.compile(filepaths=rules_to_compile)
    except yara.SyntaxError as e:
        print(f"[-] SYNTAX ERROR in rules: {e}", file=sys.stderr)
        sys.exit(1)
    except yara.Error as e:
        print(f"[-] Error compiling rules: {e}", file=sys.stderr)
        sys.exit(1)


def _iter_string_hits(match_obj):
    """
    Normalises StringMatch results across yara-python versions.

    Yields (relative_offset, identifier, data_bytes) tuples.

    yara-python >= 4.3 returns a list of StringMatch objects, each with an
    `instances` list. Older versions returned 3-tuples directly.
    """
    for s in match_obj.strings:
        if isinstance(s, tuple):
            rel_offset, ident, data = s
            yield rel_offset, ident, data
            continue

        ident = getattr(s, 'identifier', '?')
        instances = getattr(s, 'instances', None)
        if instances is None:
            continue
        for inst in instances:
            yield (
                getattr(inst, 'offset', 0),
                ident,
                getattr(inst, 'matched_data', b''),
            )


def print_match(filename, global_offset, match_obj):
    tags = f" [{', '.join(match_obj.tags)}]" if match_obj.tags else ""
    source_rule_file = match_obj.namespace if match_obj.namespace != 'main' else 'Single File'

    print(f"\n[!] MATCH FOUND in: {filename}")
    print(f"    Rule: {match_obj.rule}{tags}")
    print(f"    Rule Source: {source_rule_file}")

    for rel_offset, string_id, string_val in _iter_string_hits(match_obj):
        abs_offset = global_offset + rel_offset
        try:
            val_str = string_val.decode('utf-8', errors='replace')
        except AttributeError:
            val_str = str(string_val)
        if len(val_str) > 50:
            val_str = val_str[:47] + "..."
        print(f"    |__ Offset: 0x{abs_offset:08x} | Str: {string_id} | Data: {val_str}")


def scan_file(filepath, rules, page_size, overlap):
    """
    Scans a single file in chunks.

    `overlap` bytes from the previous chunk are prepended to the next chunk so
    that strings spanning a boundary are still detected. Reported offsets are
    relative to the original file (not the overlapped buffer).
    """
    if overlap >= page_size:
        print(f"[-] Overlap ({overlap}) must be smaller than page size ({page_size}).",
              file=sys.stderr)
        return 0

    matches_in_file = 0
    chunk_index = 0
    tail = b""

    try:
        if os.path.getsize(filepath) == 0:
            return 0

        with open(filepath, 'rb') as f:
            while True:
                chunk = f.read(page_size)
                if not chunk:
                    break

                buf = tail + chunk
                # Origin of `buf` in the original file:
                buf_origin = chunk_index * page_size - len(tail)

                try:
                    matches = rules.match(data=buf)
                except yara.Error as e:
                    print(f"[-] YARA scan error on {filepath} chunk {chunk_index}: {e}",
                          file=sys.stderr)
                    matches = []

                for m in matches:
                    matches_in_file += 1
                    print_match(filepath, buf_origin, m)

                tail = chunk[-overlap:] if overlap else b""
                chunk_index += 1

    except PermissionError:
        print(f"[-] Permission Denied: {filepath}", file=sys.stderr)
    except OSError as e:
        print(f"[-] Error scanning {filepath}: {e}", file=sys.stderr)

    return matches_in_file


def main():
    parser = argparse.ArgumentParser(description="Recursive Chunk-based YARA Scanner")

    parser.add_argument("target", help="File OR directory to analyze")
    parser.add_argument("rules", help="Path to a .yar file OR a directory of rules")
    parser.add_argument("-p", "--page-size", type=int, default=4096,
                        help="Chunk/Page size in bytes (default: 4096)")
    parser.add_argument("-O", "--overlap", type=int, default=1024,
                        help="Bytes overlapped between chunks to catch boundary "
                             "matches (default: 1024, set 0 to disable)")

    args = parser.parse_args()

    rules = compile_rules(args.rules)

    files_to_scan = []
    if os.path.isfile(args.target):
        files_to_scan.append(args.target)
    elif os.path.isdir(args.target):
        print(f"[+] Enumerating files in directory: {args.target}...")
        for root, _, files in os.walk(args.target):
            for file in files:
                files_to_scan.append(os.path.join(root, file))
    else:
        print(f"[-] Target not found: {args.target}", file=sys.stderr)
        sys.exit(1)

    print(f"[+] Target(s) identified: {len(files_to_scan)}")
    print(f"[+] Page size: {args.page_size} bytes  |  Overlap: {args.overlap} bytes")
    print("=" * 60)

    total_matches = 0
    files_scanned = 0

    try:
        for file_path in files_to_scan:
            matches = scan_file(file_path, rules, args.page_size, args.overlap)
            if matches > 0:
                total_matches += matches
                print("-" * 60)
            files_scanned += 1

    except KeyboardInterrupt:
        print("\n[!] Analysis interrupted by user.", file=sys.stderr)
        sys.exit(130)

    print("\n" + "=" * 60)
    print(f"[+] Finished.")
    print(f"[+] Files Scanned: {files_scanned}")
    print(f"[+] Total Detections: {total_matches}")


if __name__ == "__main__":
    main()
