#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
------------------------------------------------------------------------------
Script Name:   yara-chunk-scanner.py
Description:   Recursively scans files or directories using YARA rules.
               Splits files into pages (chunks) so massive dumps can be
               analyzed without loading them entirely into RAM.

               v3.2 changes:
                 - Optional `--jobs N` parallel scan when scanning a
                   directory. Each worker compiles the rules once via the
                   multiprocessing initializer, so the YARA `Rules` object
                   does not need to cross the process boundary.
                 - Workers return structured results; printing happens in
                   the main process so output is never interleaved.

Author:        Generated by Google Gemini, Revised by Ricardo J. Rodríguez
Created:       2025-11-23
Version:       3.2

Requirements:  pip install yara-python
------------------------------------------------------------------------------
"""
import argparse
import os
import sys
import multiprocessing as mp
import yara


# ---------------------------------------------------------------------------
# Rule compilation
# ---------------------------------------------------------------------------

def _build_compile_dict(path):
    """Mapping {namespace: filepath} for either a single rule file or a dir."""
    rules_to_compile = {}
    if os.path.isfile(path):
        rules_to_compile['main'] = path
    elif os.path.isdir(path):
        for root, _, files in os.walk(path):
            for f in files:
                if f.lower().endswith(('.yar', '.yara')):
                    full = os.path.join(root, f)
                    namespace = os.path.relpath(full, path).replace(os.sep, '_')
                    rules_to_compile[namespace] = full
    return rules_to_compile


def compile_rules(path):
    rules_to_compile = _build_compile_dict(path)
    if not rules_to_compile:
        if not os.path.exists(path):
            print(f"[-] Error: Rule path does not exist: {path}", file=sys.stderr)
        else:
            print("[-] Error: No .yar/.yara files found in the specified path.",
                  file=sys.stderr)
        sys.exit(1)

    print(f"[+] Compiling {len(rules_to_compile)} rule files...")
    try:
        return yara.compile(filepaths=rules_to_compile)
    except yara.SyntaxError as e:
        print(f"[-] SYNTAX ERROR in rules: {e}", file=sys.stderr)
        sys.exit(1)
    except yara.Error as e:
        print(f"[-] Error compiling rules: {e}", file=sys.stderr)
        sys.exit(1)


# ---------------------------------------------------------------------------
# Match formatting
# ---------------------------------------------------------------------------

def _iter_string_hits(match_obj):
    """
    Normalises StringMatch results across yara-python versions.

    Yields (relative_offset, identifier, data_bytes) tuples.
    """
    for s in match_obj.strings:
        if isinstance(s, tuple):
            yield s
            continue

        ident = getattr(s, 'identifier', '?')
        instances = getattr(s, 'instances', None)
        if instances is None:
            continue
        for inst in instances:
            yield (
                getattr(inst, 'offset', 0),
                ident,
                getattr(inst, 'matched_data', b''),
            )


def _format_string_hits(match_obj, global_offset):
    """Returns picklable list of dicts (so workers can ship them home)."""
    out = []
    for rel_offset, ident, data in _iter_string_hits(match_obj):
        try:
            data_str = data.decode('utf-8', errors='replace') if isinstance(data, (bytes, bytearray)) else str(data)
        except Exception:
            data_str = "<undecodable>"
        out.append({
            "abs_offset": global_offset + rel_offset,
            "id": ident,
            "data": data_str[:50] + ("..." if len(data_str) > 50 else ""),
        })
    return out


def print_file_findings(findings):
    if not findings:
        return
    filepath = findings[0]["file"]
    for f in findings:
        tags = f" [{', '.join(f['tags'])}]" if f['tags'] else ""
        ns = f['namespace'] if f['namespace'] != 'main' else 'Single File'

        print(f"\n[!] MATCH FOUND in: {filepath}")
        print(f"    Rule: {f['rule']}{tags}")
        print(f"    Rule Source: {ns}")
        for h in f['hits']:
            print(f"    |__ Offset: 0x{h['abs_offset']:08x} | Str: {h['id']} | Data: {h['data']}")
    print("-" * 60)


# ---------------------------------------------------------------------------
# Scanning
# ---------------------------------------------------------------------------

def scan_file(filepath, rules, page_size, overlap):
    """
    Scans a single file in chunks, returns a list of structured findings.
    `overlap` bytes from the previous chunk are prepended to the next chunk
    so strings spanning a boundary are still detected. Reported offsets are
    relative to the original file (not the overlapped buffer).
    """
    if overlap >= page_size:
        return [{"_error": f"Overlap ({overlap}) must be smaller than page size ({page_size})."}]

    findings = []
    try:
        if os.path.getsize(filepath) == 0:
            return findings
    except OSError as e:
        return [{"_error": f"stat failed on {filepath}: {e}"}]

    chunk_index = 0
    tail = b""

    try:
        with open(filepath, 'rb') as f:
            while True:
                chunk = f.read(page_size)
                if not chunk:
                    break

                buf = tail + chunk
                buf_origin = chunk_index * page_size - len(tail)

                try:
                    matches = rules.match(data=buf)
                except yara.Error as e:
                    findings.append({
                        "_error": f"YARA scan error on {filepath} chunk {chunk_index}: {e}"
                    })
                    matches = []

                for m in matches:
                    findings.append({
                        "file": filepath,
                        "rule": m.rule,
                        "namespace": m.namespace,
                        "tags": list(m.tags),
                        "hits": _format_string_hits(m, buf_origin),
                    })

                tail = chunk[-overlap:] if overlap else b""
                chunk_index += 1

    except PermissionError:
        return [{"_error": f"Permission Denied: {filepath}"}]
    except OSError as e:
        return [{"_error": f"Error scanning {filepath}: {e}"}]

    return findings


# ---------------------------------------------------------------------------
# Multiprocessing plumbing
# ---------------------------------------------------------------------------

# Globals populated by the worker initializer. The Rules object stays inside
# the worker process — it is not pickled across the IPC boundary.
_W_RULES = None
_W_PAGE = None
_W_OVERLAP = None


def _worker_init(rules_path, page, overlap):
    global _W_RULES, _W_PAGE, _W_OVERLAP
    _W_RULES = compile_rules(rules_path)
    _W_PAGE = page
    _W_OVERLAP = overlap


def _worker_scan(filepath):
    return filepath, scan_file(filepath, _W_RULES, _W_PAGE, _W_OVERLAP)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Recursive Chunk-based YARA Scanner")
    parser.add_argument("target", help="File OR directory to analyze")
    parser.add_argument("rules", help="Path to a .yar file OR a directory of rules")
    parser.add_argument("-p", "--page-size", type=int, default=4096,
                        help="Chunk/Page size in bytes (default: 4096)")
    parser.add_argument("-O", "--overlap", type=int, default=1024,
                        help="Bytes overlapped between chunks to catch boundary "
                             "matches (default: 1024, set 0 to disable)")
    parser.add_argument("-j", "--jobs", type=int, default=1,
                        help="Parallel workers for directory scans (default: 1). "
                             "Each worker compiles rules independently.")
    args = parser.parse_args()

    files_to_scan = []
    if os.path.isfile(args.target):
        files_to_scan.append(args.target)
    elif os.path.isdir(args.target):
        print(f"[+] Enumerating files in directory: {args.target}...")
        for root, _, files in os.walk(args.target):
            for f in files:
                files_to_scan.append(os.path.join(root, f))
    else:
        print(f"[-] Target not found: {args.target}", file=sys.stderr)
        sys.exit(1)

    print(f"[+] Target(s) identified: {len(files_to_scan)}")
    print(f"[+] Page size: {args.page_size} bytes  |  Overlap: {args.overlap} bytes  |  Jobs: {args.jobs}")
    print("=" * 60)

    total_matches = 0
    files_scanned = 0
    use_pool = args.jobs > 1 and len(files_to_scan) > 1

    try:
        if use_pool:
            with mp.Pool(processes=args.jobs,
                         initializer=_worker_init,
                         initargs=(args.rules, args.page_size, args.overlap)) as pool:
                for filepath, findings in pool.imap_unordered(_worker_scan, files_to_scan):
                    files_scanned += 1
                    real_findings = [f for f in findings if "_error" not in f]
                    for err in (f for f in findings if "_error" in f):
                        print(f"[-] {err['_error']}", file=sys.stderr)
                    total_matches += len(real_findings)
                    print_file_findings(real_findings)
        else:
            rules = compile_rules(args.rules)
            for file_path in files_to_scan:
                findings = scan_file(file_path, rules, args.page_size, args.overlap)
                files_scanned += 1
                real_findings = [f for f in findings if "_error" not in f]
                for err in (f for f in findings if "_error" in f):
                    print(f"[-] {err['_error']}", file=sys.stderr)
                total_matches += len(real_findings)
                print_file_findings(real_findings)

    except KeyboardInterrupt:
        print("\n[!] Analysis interrupted by user.", file=sys.stderr)
        sys.exit(130)

    print("\n" + "=" * 60)
    print(f"[+] Finished.")
    print(f"[+] Files Scanned: {files_scanned}")
    print(f"[+] Total Detections: {total_matches}")


if __name__ == "__main__":
    main()
